export default [
  {
    "id": "solar-system-galactic-distance",
    "category": "cosmic",
    "label": "the Solar System has travelled",
    "rate": 220,
    "period": "second",
    "unit": "km through the Milky Way",
    "decimalPlaces": 0,
    "format": "number",
    "sourceLabel": null,
    "sourceUrl": null
  },
  {
    "id": "earth-orbital-distance",
    "category": "cosmic",
    "label": "Earth has travelled",
    "rate": 29.78,
    "period": "second",
    "unit": "km around the Sun",
    "decimalPlaces": 0,
    "format": "number",
    "sourceLabel": null,
    "sourceUrl": null
  },
  {
    "id": "moon-orbital-distance",
    "category": "cosmic",
    "label": "the Moon has travelled",
    "rate": 1.022,
    "period": "second",
    "unit": "km around Earth",
    "decimalPlaces": 0,
    "format": "number",
    "sourceLabel": null,
    "sourceUrl": null
  },
  {
    "id": "iss-distance",
    "category": "cosmic",
    "label": "the International Space Station has travelled",
    "rate": 7.66,
    "period": "second",
    "unit": "km above Earth",
    "decimalPlaces": 0,
    "format": "number",
    "sourceLabel": null,
    "sourceUrl": null
  },
  {
    "id": "equator-distance",
    "category": "cosmic",
    "label": "a point on Earth's equator has travelled",
    "rate": 0.465,
    "period": "second",
    "unit": "km through its daily spin",
    "decimalPlaces": 0,
    "format": "number",
    "sourceLabel": null,
    "sourceUrl": null
  },
  {
    "id": "light-speed-frontier",
    "category": "cosmic",
    "label": "a light-speed signal could have travelled",
    "rate": 299792.458,
    "period": "second",
    "unit": "km from Earth",
    "decimalPlaces": 0,
    "format": "number",
    "sourceLabel": null,
    "sourceUrl": null
  },
  {
    "id": "solar-mass-converted",
    "category": "cosmic",
    "label": "the Sun has converted",
    "rate": 4260000,
    "period": "second",
    "unit": "tonnes of itself into light",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": null,
    "sourceUrl": null
  },
  {
    "id": "solar-energy-received",
    "category": "cosmic",
    "label": "sunlight has delivered",
    "rate": 174,
    "period": "second",
    "unit": "petajoules to Earth",
    "decimalPlaces": 0,
    "format": "number",
    "sourceLabel": null,
    "sourceUrl": null
  },
  {
    "id": "solar-neutrinos",
    "category": "cosmic",
    "label": "solar neutrinos have passed through every square centimetre of you",
    "rate": 65000000000,
    "period": "second",
    "unit": "neutrinos",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": null,
    "sourceUrl": null
  },
  {
    "id": "cosmic-dust",
    "category": "cosmic",
    "label": "cosmic dust has settled onto Earth",
    "rate": 0.6,
    "period": "second",
    "unit": "kg",
    "decimalPlaces": 1,
    "format": "number",
    "sourceLabel": null,
    "sourceUrl": null
  },
  {
    "id": "lightning-flashes",
    "category": "planetary",
    "label": "lightning flashes have crossed the planet",
    "rate": 44,
    "period": "second",
    "unit": "flashes",
    "decimalPlaces": 0,
    "format": "number",
    "sourceLabel": null,
    "sourceUrl": null
  },
  {
    "id": "water-evaporated",
    "category": "planetary",
    "label": "water has entered the atmosphere",
    "rate": 16000000,
    "period": "second",
    "unit": "m³ through evaporation",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": null,
    "sourceUrl": null
  },
  {
    "id": "co2-emitted",
    "category": "planetary",
    "label": "carbon dioxide has been emitted",
    "rate": 1200,
    "period": "second",
    "unit": "tonnes of CO₂",
    "decimalPlaces": 0,
    "format": "number",
    "sourceLabel": null,
    "sourceUrl": null
  },
  {
    "id": "oxygen-released",
    "category": "planetary",
    "label": "photosynthesis has released",
    "rate": 3000,
    "period": "second",
    "unit": "tonnes of oxygen",
    "decimalPlaces": 0,
    "format": "number",
    "sourceLabel": null,
    "sourceUrl": null
  },
  {
    "id": "forest-cleared",
    "category": "planetary",
    "label": "forest has been cleared",
    "rate": 0.32,
    "period": "second",
    "unit": "hectares",
    "decimalPlaces": 2,
    "format": "number",
    "sourceLabel": null,
    "sourceUrl": null
  },
  {
    "id": "plastic-produced",
    "category": "materials",
    "label": "plastic has been produced",
    "rate": 12.7,
    "period": "second",
    "unit": "tonnes",
    "decimalPlaces": 0,
    "format": "number",
    "sourceLabel": null,
    "sourceUrl": null
  },
  {
    "id": "cement-produced",
    "category": "materials",
    "label": "cement has been produced",
    "rate": 140,
    "period": "second",
    "unit": "tonnes",
    "decimalPlaces": 0,
    "format": "number",
    "sourceLabel": null,
    "sourceUrl": null
  },
  {
    "id": "energy-used",
    "category": "materials",
    "label": "humanity has used",
    "rate": 19,
    "period": "second",
    "unit": "terajoules of energy",
    "decimalPlaces": 0,
    "format": "number",
    "sourceLabel": null,
    "sourceUrl": null
  },
  {
    "id": "freshwater-withdrawn",
    "category": "materials",
    "label": "freshwater has been withdrawn",
    "rate": 130000,
    "period": "second",
    "unit": "m³ for human use",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": null,
    "sourceUrl": null
  },
  {
    "id": "oil-used",
    "category": "materials",
    "label": "the world has used",
    "rate": 184000,
    "period": "second",
    "unit": "litres of oil",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": null,
    "sourceUrl": null
  },
  {
    "id": "births",
    "category": "human",
    "label": "the world has welcomed",
    "rate": 4.2,
    "period": "second",
    "unit": "people",
    "decimalPlaces": 0,
    "format": "number",
    "sourceLabel": null,
    "sourceUrl": null
  },
  {
    "id": "deaths",
    "category": "human",
    "label": "the world has lost",
    "rate": 2,
    "period": "second",
    "unit": "people",
    "decimalPlaces": 0,
    "format": "number",
    "sourceLabel": null,
    "sourceUrl": null
  },
  {
    "id": "human-heartbeats",
    "category": "human",
    "label": "human hearts have beaten",
    "rate": 9300000000,
    "period": "second",
    "unit": "beats",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": null,
    "sourceUrl": null
  },
  {
    "id": "human-breaths",
    "category": "human",
    "label": "human breaths have been taken",
    "rate": 1600000000,
    "period": "second",
    "unit": "breaths",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": null,
    "sourceUrl": null
  },
  {
    "id": "meals-eaten",
    "category": "human",
    "label": "the world has eaten",
    "rate": 277778,
    "period": "second",
    "unit": "meals",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": null,
    "sourceUrl": null
  },
  {
    "id": "words-spoken",
    "category": "human",
    "label": "the world has spoken",
    "rate": 1500000000,
    "period": "second",
    "unit": "words",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": null,
    "sourceUrl": null
  },
  {
    "id": "coffee-consumed",
    "category": "human",
    "label": "the world has drunk",
    "rate": 26000,
    "period": "second",
    "unit": "cups of coffee",
    "decimalPlaces": 0,
    "format": "number",
    "sourceLabel": null,
    "sourceUrl": null
  },
  {
    "id": "eggs-laid",
    "category": "human",
    "label": "chickens have laid",
    "rate": 47000,
    "period": "second",
    "unit": "eggs",
    "decimalPlaces": 0,
    "format": "number",
    "sourceLabel": null,
    "sourceUrl": null
  },
  {
    "id": "air-passengers",
    "category": "infrastructure",
    "label": "aircraft have carried",
    "rate": 150,
    "period": "second",
    "unit": "passengers",
    "decimalPlaces": 0,
    "format": "number",
    "sourceLabel": null,
    "sourceUrl": null
  },
  {
    "id": "parcels-shipped",
    "category": "infrastructure",
    "label": "parcels have begun a journey",
    "rate": 5000,
    "period": "second",
    "unit": "parcels",
    "decimalPlaces": 0,
    "format": "number",
    "sourceLabel": null,
    "sourceUrl": null
  },
  {
    "id": "emails-sent",
    "category": "network",
    "label": "the internet has sent",
    "rate": 3500000,
    "period": "second",
    "unit": "emails",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": null,
    "sourceUrl": null
  },
  {
    "id": "web-searches",
    "category": "network",
    "label": "the web has answered",
    "rate": 100000,
    "period": "second",
    "unit": "searches",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": null,
    "sourceUrl": null
  },
  {
    "id": "text-messages",
    "category": "network",
    "label": "the world has exchanged",
    "rate": 250000,
    "period": "second",
    "unit": "text messages",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": null,
    "sourceUrl": null
  },
  {
    "id": "photos-taken",
    "category": "network",
    "label": "photos have been taken",
    "rate": 63000,
    "period": "second",
    "unit": "photos",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": null,
    "sourceUrl": null
  },
  {
    "id": "video-uploaded",
    "category": "network",
    "label": "video has been uploaded",
    "rate": 8.3,
    "period": "second",
    "unit": "hours of footage",
    "decimalPlaces": 0,
    "format": "number",
    "sourceLabel": null,
    "sourceUrl": null
  },
  {
    "id": "songs-streamed",
    "category": "culture",
    "label": "songs have been streamed",
    "rate": 60000,
    "period": "second",
    "unit": "plays",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": null,
    "sourceUrl": null
  },
  {
    "id": "online-payments",
    "category": "culture",
    "label": "online commerce has processed",
    "rate": 50000,
    "period": "second",
    "unit": "payments",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": null,
    "sourceUrl": null
  },
  {
    "id": "wikipedia-edits",
    "category": "culture",
    "label": "Wikipedia has received",
    "rate": 2,
    "period": "second",
    "unit": "edits",
    "decimalPlaces": 0,
    "format": "number",
    "sourceLabel": null,
    "sourceUrl": null
  },
  {
    "id": "grain-harvested",
    "category": "food",
    "label": "fields have yielded",
    "rate": 90000,
    "period": "second",
    "unit": "kg of grain",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": null,
    "sourceUrl": null
  },
  {
    "id": "milk-produced",
    "category": "food",
    "label": "dairies have produced",
    "rate": 28500,
    "period": "second",
    "unit": "litres of milk",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": null,
    "sourceUrl": null
  },
  {
    "id": "crayola-crayons",
    "category": "play",
    "label": "Crayola has made",
    "rate": 95.064263442,
    "period": "second",
    "unit": "crayons",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "Crayola annual production FAQ",
    "sourceUrl": "https://www.crayola.com/faqs/how-many-crayola-products-do-you-make-per-year-faq"
  },
  {
    "id": "crayola-colored-pencils",
    "category": "play",
    "label": "Crayola has made",
    "rate": 19.012852688,
    "period": "second",
    "unit": "coloured pencils",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "Crayola annual production FAQ",
    "sourceUrl": "https://www.crayola.com/faqs/how-many-crayola-products-do-you-make-per-year-faq"
  },
  {
    "id": "crayola-markers",
    "category": "play",
    "label": "Crayola has made",
    "rate": 14.734960834,
    "period": "second",
    "unit": "markers",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "Crayola annual production FAQ",
    "sourceUrl": "https://www.crayola.com/faqs/how-many-crayola-products-do-you-make-per-year-faq"
  },
  {
    "id": "crayola-chalk",
    "category": "play",
    "label": "Crayola has made",
    "rate": 3.48568966,
    "period": "second",
    "unit": "sticks of chalk",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "Crayola annual production FAQ",
    "sourceUrl": "https://www.crayola.com/faqs/how-many-crayola-products-do-you-make-per-year-faq"
  },
  {
    "id": "crayola-silly-putty-eggs",
    "category": "play",
    "label": "Crayola has made",
    "rate": 0.28519279,
    "period": "second",
    "unit": "Silly Putty eggs",
    "decimalPlaces": 0,
    "format": "number",
    "sourceLabel": "Crayola annual production FAQ",
    "sourceUrl": "https://www.crayola.com/faqs/how-many-crayola-products-do-you-make-per-year-faq"
  },
  {
    "id": "crayola-paint-jars",
    "category": "play",
    "label": "Crayola has filled",
    "rate": 0.047532132,
    "period": "second",
    "unit": "jars of paint",
    "decimalPlaces": 0,
    "format": "number",
    "sourceLabel": "Crayola annual production FAQ",
    "sourceUrl": "https://www.crayola.com/faqs/how-many-crayola-products-do-you-make-per-year-faq"
  },
  {
    "id": "ben-jerrys-pints",
    "category": "food",
    "label": "the Ben & Jerry’s Waterbury factory has churned",
    "rate": 4.050925926,
    "period": "second",
    "unit": "pints of ice cream",
    "decimalPlaces": 0,
    "format": "number",
    "sourceLabel": "Ben & Jerry’s Waterbury factory tour",
    "sourceUrl": "https://www.benjerry.com/about-us/factory-tours"
  },
  {
    "id": "greeting-cards-purchased",
    "category": "celebration",
    "label": "Americans have picked out",
    "rate": 205.972570791,
    "period": "second",
    "unit": "greeting cards",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "Hallmark, citing the Greeting Card Association",
    "sourceUrl": "https://corporate.hallmark.com/hallmark-news/greetings/"
  },
  {
    "id": "public-library-visits",
    "category": "culture",
    "label": "have happened in U.S. public libraries",
    "rate": 25.350470251,
    "period": "second",
    "unit": "public-library visits",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "IMLS 2023 public library survey data",
    "sourceUrl": "https://content.govdelivery.com/accounts/USIMLS/bulletins/3f09e4a"
  },
  {
    "id": "pokemon-cards-printed",
    "category": "games",
    "label": "The Pokémon Company has printed",
    "rate": 316.88087814,
    "period": "second",
    "unit": "Pokémon cards",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "IGN reporting Pokémon Company card production",
    "sourceUrl": "https://www.ign.com/articles/10-billion-pokemon-cards-were-printed-last-year-and-it-still-wasnt-enough-to-stop-shortages-and-scalping"
  },
  {
    "id": "lego-kids-reached",
    "category": "play",
    "label": "LEGO play initiatives have reached",
    "rate": 0.380257054,
    "period": "second",
    "unit": "children",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "LEGO Group Annual Report 2024",
    "sourceUrl": "https://www.lego.com/cdn/cs/aboutus/assets/blt1cdf90a38318ef56/the_LEGO_Group_Annual_Report_2024.pdf"
  },
  {
    "id": "lego-play-downloads",
    "category": "play",
    "label": "the LEGO Play app has received",
    "rate": 0.158440439,
    "period": "second",
    "unit": "downloads",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "LEGO Group Annual Report 2024",
    "sourceUrl": "https://www.lego.com/cdn/cs/aboutus/assets/blt1cdf90a38318ef56/the_LEGO_Group_Annual_Report_2024.pdf"
  },
  {
    "id": "ps5-consoles-shipped",
    "category": "games",
    "label": "Sony has shipped",
    "rate": 0.586229625,
    "period": "second",
    "unit": "PlayStation 5 consoles",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "Sony Interactive Entertainment FY2024 sales data",
    "sourceUrl": "https://sonyinteractive.com/en/our-company/business-data-sales/"
  },
  {
    "id": "playstation-games-sold",
    "category": "games",
    "label": "Sony has shipped",
    "rate": 9.610997034,
    "period": "second",
    "unit": "PlayStation game copies",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "Sony Interactive Entertainment FY2024 sales data",
    "sourceUrl": "https://sonyinteractive.com/en/our-company/business-data-sales/"
  },
  {
    "id": "switch-consoles-sold",
    "category": "games",
    "label": "Nintendo has sold",
    "rate": 0.497502979,
    "period": "second",
    "unit": "Switch consoles",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "Nintendo FY2024 financial results",
    "sourceUrl": "https://www.nintendo.co.jp/ir/pdf/2024/240507e.pdf"
  },
  {
    "id": "switch-games-sold",
    "category": "games",
    "label": "Nintendo has sold",
    "rate": 5.195261997,
    "period": "second",
    "unit": "Switch game copies",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "Nintendo FY2024 financial results",
    "sourceUrl": "https://www.nintendo.co.jp/ir/pdf/2024/240507e.pdf"
  },
  {
    "id": "uber-trips",
    "category": "travel",
    "label": "the Uber platform has completed",
    "rate": 354.906583517,
    "period": "second",
    "unit": "trips",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "Uber full-year 2024 results",
    "sourceUrl": "https://investor.uber.com/news-events/news/press-release-details/2025/Uber-Announces-Results-for-Fourth-Quarter-and-Full-Year-2024/default.aspx"
  },
  {
    "id": "lyft-rides",
    "category": "travel",
    "label": "people have taken",
    "rate": 26.23773671,
    "period": "second",
    "unit": "Lyft rides",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "Lyft full-year 2024 results",
    "sourceUrl": "https://investor.lyft.com/news-events-presentations/press-releases/detail/103/lyft-reports-record-q4-and-full-year-2024-results"
  },
  {
    "id": "airbnb-bookings",
    "category": "travel",
    "label": "have been made on Airbnb",
    "rate": 15.558851117,
    "period": "second",
    "unit": "Airbnb bookings",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "Airbnb Q4 and full-year 2024 results",
    "sourceUrl": "https://news.airbnb.com/airbnb-q4-2024-financial-results/"
  },
  {
    "id": "amtrak-trips",
    "category": "travel",
    "label": "people have taken",
    "rate": 1.03936928,
    "period": "second",
    "unit": "Amtrak trips",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "Amtrak FY2024 ridership release",
    "sourceUrl": "https://media.amtrak.com/2024/12/amtrak-sets-all-time-ridership-record-in-fiscal-year-2024/"
  },
  {
    "id": "tsa-screenings",
    "category": "travel",
    "label": "have passed through U.S. airport security",
    "rate": 28.646031384,
    "period": "second",
    "unit": "travellers",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "TSA 2024 checkpoint travel numbers",
    "sourceUrl": "https://www.tsa.gov/travel/passenger-volumes"
  },
  {
    "id": "nhl-attendance",
    "category": "sports",
    "label": "hockey fans have filled",
    "rate": 0.729284166,
    "period": "second",
    "unit": "NHL arena seats",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "NHL 2024–25 regular-season attendance",
    "sourceUrl": "https://www.nhl.com/news/nhl-sets-regular-season-attendance-record-in-2024-2025"
  },
  {
    "id": "usps-mail-pieces",
    "category": "delivery",
    "label": "the U.S. Postal Service has handled",
    "rate": 3571.247496641,
    "period": "second",
    "unit": "mail pieces",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "USPS FY2024 Annual Report",
    "sourceUrl": "https://about.usps.com/what/financials/annual-reports/fy2024.pdf"
  },
  {
    "id": "ups-packages",
    "category": "delivery",
    "label": "UPS has delivered",
    "rate": 167.946865414,
    "period": "second",
    "unit": "packages",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "UPS 2024 Annual Report",
    "sourceUrl": "https://about.ups.com/us/en/our-company/annual-report.html"
  },
  {
    "id": "recorded-music-revenue",
    "category": "music",
    "label": "U.S. recorded music has brought in",
    "rate": 560.879154308,
    "period": "second",
    "unit": "dollars in revenue",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "RIAA 2024 year-end revenue report",
    "sourceUrl": "https://www.riaa.com/reports/2024-riaa-year-end-revenue-report/"
  },
  {
    "id": "nyc-subway-rides",
    "category": "city",
    "label": "New Yorkers and visitors have taken",
    "rate": 37.867264938,
    "period": "second",
    "unit": "subway rides",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "MTA 2024 ridership statistics",
    "sourceUrl": "https://metrics.mta.info/?subway"
  },
  {
    "id": "nyc-bus-rides",
    "category": "city",
    "label": "New Yorkers and visitors have taken",
    "rate": 18.379090932,
    "period": "second",
    "unit": "city bus rides",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "MTA 2024 ridership statistics",
    "sourceUrl": "https://metrics.mta.info/?subway"
  },
  {
    "id": "national-park-visits",
    "category": "parks",
    "label": "have visited U.S. national parks",
    "rate": 10.516115231,
    "period": "second",
    "unit": "people",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "National Park Service 2024 visitation data",
    "sourceUrl": "https://www.nps.gov/aboutus/visitation-numbers.htm"
  },
  {
    "id": "great-smoky-mountains-visits",
    "category": "parks",
    "label": "have found their way into Great Smoky Mountains",
    "rate": 0.386335906,
    "period": "second",
    "unit": "people",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "National Park Service 2024 visitation data",
    "sourceUrl": "https://www.nps.gov/aboutus/visitation-numbers.htm"
  },
  {
    "id": "zion-visits",
    "category": "parks",
    "label": "have wandered through Zion",
    "rate": 0.156748042,
    "period": "second",
    "unit": "people",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "National Park Service 2024 visitation data",
    "sourceUrl": "https://www.nps.gov/aboutus/visitation-numbers.htm"
  },
  {
    "id": "grand-canyon-visits",
    "category": "parks",
    "label": "have stood at the Grand Canyon",
    "rate": 0.155900132,
    "period": "second",
    "unit": "people",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "National Park Service 2024 visitation data",
    "sourceUrl": "https://www.nps.gov/aboutus/visitation-numbers.htm"
  },
  {
    "id": "yellowstone-visits",
    "category": "parks",
    "label": "have visited Yellowstone",
    "rate": 0.150332345,
    "period": "second",
    "unit": "people",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "National Park Service 2024 visitation data",
    "sourceUrl": "https://www.nps.gov/aboutus/visitation-numbers.htm"
  },
  {
    "id": "rocky-mountain-visits",
    "category": "parks",
    "label": "have hiked Rocky Mountain National Park",
    "rate": 0.131643376,
    "period": "second",
    "unit": "people",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "National Park Service 2024 visitation data",
    "sourceUrl": "https://www.nps.gov/aboutus/visitation-numbers.htm"
  },
  {
    "id": "yosemite-visits",
    "category": "parks",
    "label": "have visited Yosemite",
    "rate": 0.130591458,
    "period": "second",
    "unit": "people",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "National Park Service 2024 visitation data",
    "sourceUrl": "https://www.nps.gov/aboutus/visitation-numbers.htm"
  },
  {
    "id": "mlb-attendance",
    "category": "sports",
    "label": "baseball fans have filled",
    "rate": 2.260893287,
    "period": "second",
    "unit": "MLB stadium seats",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "MLB 2024 attendance release",
    "sourceUrl": "https://www.mlb.com/press-release/press-release-mlb-finishes-2024-season-with-highest-attendance-in-seven-years"
  },
  {
    "id": "nba-attendance",
    "category": "sports",
    "label": "basketball fans have filled",
    "rate": 0.714202538,
    "period": "second",
    "unit": "NBA arena seats",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "NBA 2023–24 regular-season attendance release",
    "sourceUrl": "https://www.nba.com/news/nba-sets-all-time-record-for-attendance-and-sellouts-during-2023-24-regular-season"
  },
  {
    "id": "acadia-visits",
    "category": "parks",
    "label": "have explored Acadia",
    "rate": 0.125537462,
    "period": "second",
    "unit": "people",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "National Park Service 2024 visitation data",
    "sourceUrl": "https://www.nps.gov/aboutus/visitation-numbers.htm"
  },
  {
    "id": "grand-teton-visits",
    "category": "parks",
    "label": "have visited Grand Teton",
    "rate": 0.114971417,
    "period": "second",
    "unit": "people",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "National Park Service 2024 visitation data",
    "sourceUrl": "https://www.nps.gov/aboutus/visitation-numbers.htm"
  },
  {
    "id": "olympic-visits",
    "category": "parks",
    "label": "have visited Olympic National Park",
    "rate": 0.117793083,
    "period": "second",
    "unit": "people",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "National Park Service 2024 visitation data",
    "sourceUrl": "https://www.nps.gov/aboutus/visitation-numbers.htm"
  },
  {
    "id": "coca-cola-servings",
    "category": "food",
    "label": "of Coca-Cola have been enjoyed",
    "rate": 25462.962962963,
    "period": "second",
    "unit": "servings",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "The Coca-Cola Company fact sheet",
    "sourceUrl": "https://www.coca-colacompany.com/about-us"
  },
  {
    "id": "mcdonalds-customers",
    "category": "food",
    "label": "McDonald’s has served",
    "rate": 729.166666667,
    "period": "second",
    "unit": "customers",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "McDonald’s company profile",
    "sourceUrl": "https://corporate.mcdonalds.com/corpmcd/our-company/who-we-are.html"
  },
  {
    "id": "nescafe-cups",
    "category": "food",
    "label": "of Nescafé have been enjoyed",
    "rate": 6000,
    "period": "second",
    "unit": "cups",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "Nestlé Nescafé announcement",
    "sourceUrl": "https://www.nestle.com/media/news/nescafe-ice-roast-coffee-launch"
  },
  {
    "id": "guinness-glasses",
    "category": "food",
    "label": "of Guinness have been enjoyed",
    "rate": 115.740740741,
    "period": "second",
    "unit": "glasses",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "Guinness FAQ",
    "sourceUrl": "https://www.guinness.com/en-us/frequently-asked-questions"
  },
  {
    "id": "walmart-customer-visits",
    "category": "commerce",
    "label": "Walmart has welcomed",
    "rate": 462.962962963,
    "period": "second",
    "unit": "customer visits",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "Walmart company facts",
    "sourceUrl": "https://corporate.walmart.com/about"
  },
  {
    "id": "walmart-items-moved",
    "category": "commerce",
    "label": "Walmart’s supply chain has moved",
    "rate": 3168.808781403,
    "period": "second",
    "unit": "items",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "Walmart company facts",
    "sourceUrl": "https://corporate.walmart.com/about"
  },
  {
    "id": "pepsico-servings",
    "category": "food",
    "label": "of PepsiCo products have been enjoyed",
    "rate": 11574.074074074,
    "period": "second",
    "unit": "servings",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "PepsiCo company facts",
    "sourceUrl": "https://www.pepsico.com/about"
  },
  {
    "id": "unilever-product-users",
    "category": "personal-care",
    "label": "have used Unilever products",
    "rate": 42824.074074074,
    "period": "second",
    "unit": "people",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "Unilever brand facts",
    "sourceUrl": "https://www.unilever.com/brands/"
  },
  {
    "id": "oreo-cookies-made",
    "category": "food",
    "label": "Oreo factories have made",
    "rate": 1267.523512561,
    "period": "second",
    "unit": "cookies",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "Mondelēz Oreo facts",
    "sourceUrl": "https://www.mondelezinternational.com/News/Oreo-Little-Known-Facts/"
  },
  {
    "id": "hershey-kisses-made",
    "category": "food",
    "label": "the West Hershey plant has made",
    "rate": 810.185185185,
    "period": "second",
    "unit": "Hershey’s Kisses",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "The Hershey Company plant facts",
    "sourceUrl": "https://www.thehersheycompany.com/en_us/home/about-us/the-company/plant-locations.html"
  },
  {
    "id": "ikea-food-balls-sold",
    "category": "food",
    "label": "IKEA has sold",
    "rate": 44.36332294,
    "period": "second",
    "unit": "food balls",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "IKEA’s 40 years of meatballs",
    "sourceUrl": "https://www.ikea.com/global/en/stories/our-roots/meatball-40-years-251024/"
  },
  {
    "id": "bic-products-made",
    "category": "everyday",
    "label": "BIC factories have made",
    "rate": 274.305555556,
    "period": "second",
    "unit": "products",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "BIC creations and innovations",
    "sourceUrl": "https://corporate.bic.com/en-us/group/our-creations"
  },
  {
    "id": "hot-wheels-sold",
    "category": "play",
    "label": "have been sold",
    "rate": 16.5,
    "period": "second",
    "unit": "Hot Wheels cars",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "PLAION press release quoting Hot Wheels figures",
    "sourceUrl": "https://press.plaion.com/-Hot-Wheels-Unleashed-Sold-One-Million-Copies-Worldwide"
  },
  {
    "id": "lego-bricks-made",
    "category": "play",
    "label": "have been made",
    "rate": 1140.771161305,
    "period": "second",
    "unit": "LEGO bricks",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "LEGOLAND Discovery Center LEGO facts",
    "sourceUrl": "https://www.legolanddiscoverycenter.com/michigan/post/lego-facts/"
  },
  {
    "id": "tesla-vehicles-made",
    "category": "vehicles",
    "label": "have rolled off Tesla production lines",
    "rate": 0.056197018,
    "period": "second",
    "unit": "vehicles",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "Tesla 2024 production and deliveries",
    "sourceUrl": "https://ir.tesla.com/press-release/tesla-fourth-quarter-2024-production-deliveries-and-deployments"
  },
  {
    "id": "tesla-vehicles-delivered",
    "category": "vehicles",
    "label": "Tesla has delivered",
    "rate": 0.056697151,
    "period": "second",
    "unit": "vehicles",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "Tesla 2024 production and deliveries",
    "sourceUrl": "https://ir.tesla.com/press-release/tesla-fourth-quarter-2024-production-deliveries-and-deployments"
  },
  {
    "id": "toyota-us-sales",
    "category": "vehicles",
    "label": "Toyota and Lexus have sold in the U.S.",
    "rate": 0.073916362,
    "period": "second",
    "unit": "vehicles",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "Toyota Motor North America 2024 sales",
    "sourceUrl": "https://pressroom.toyota.com/toyota-motor-north-america-reports-2024-u-s-sales-results/"
  },
  {
    "id": "crocs-shoes-sold",
    "category": "fashion",
    "label": "Crocs has sold",
    "rate": 4.024387152,
    "period": "second",
    "unit": "pairs of shoes",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "Crocs 2024 full-year results transcript",
    "sourceUrl": "https://s22.q4cdn.com/133460125/files/doc_financials/2024/q4/Q4-FY-2024-Crocs-Inc-Transcript.pdf"
  },
  {
    "id": "doordash-orders",
    "category": "delivery",
    "label": "have been placed",
    "rate": 81.850330824,
    "period": "second",
    "unit": "DoorDash orders",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "DoorDash 2024 quarterly results (annual sum)",
    "sourceUrl": "https://ir.doordash.com/news/news-details/2025/DoorDash-Releases-Fourth-Quarter-and-Full-Year-2024-Financial-Results/default.aspx"
  },
  {
    "id": "airbus-deliveries",
    "category": "aviation",
    "label": "Airbus has delivered",
    "rate": 0.000024273,
    "period": "second",
    "unit": "commercial airplanes",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "Airbus 2024 deliveries",
    "sourceUrl": "https://www.airbus.com/en/newsroom/press-releases/2025-01-airbus-reports-766-commercial-aircraft-deliveries-in-2024",
    "minimumElapsedSeconds": 43200
  },
  {
    "id": "boeing-deliveries",
    "category": "aviation",
    "label": "Boeing has delivered",
    "rate": 0.000011027,
    "period": "second",
    "unit": "commercial airplanes",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "Boeing 2024 fourth-quarter results",
    "sourceUrl": "https://investors.boeing.com/investors/news/press-release-details/2025/Boeing-Reports-Fourth-Quarter-Results/default.aspx",
    "minimumElapsedSeconds": 86400
  },
  {
    "id": "ferrari-shipments",
    "category": "vehicles",
    "label": "Ferrari has shipped",
    "rate": 0.000435775,
    "period": "second",
    "unit": "cars",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "Ferrari 2024 full-year results",
    "sourceUrl": "https://www.ferrari.com/en-EN/corporate/articles/2024-full-year-and-fourth-quarter-financial-results",
    "minimumElapsedSeconds": 3600
  },
  {
    "id": "global-beer-consumption",
    "category": "food",
    "label": "of beer has been enjoyed worldwide",
    "rate": 6151.291606459,
    "period": "second",
    "unit": "litres",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "Kirin Global Beer Consumption Report 2024",
    "sourceUrl": "https://www.kirinholdings.com/en/newsroom/release/2025/1222_01.pdf"
  },
  {
    "id": "global-wine-production",
    "category": "food",
    "label": "of wine has been made worldwide",
    "rate": 715.517022841,
    "period": "second",
    "unit": "litres",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "OIV State of the World Vine and Wine Sector 2024",
    "sourceUrl": "https://www.oiv.int/sites/default/files/2025-04/OIV-State_of_the_World_Vine-and-Wine-Sector-in-2024.pdf"
  },
  {
    "id": "global-wine-consumption",
    "category": "food",
    "label": "of wine has been enjoyed worldwide",
    "rate": 678.758840977,
    "period": "second",
    "unit": "litres",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "OIV State of the World Vine and Wine Sector 2024",
    "sourceUrl": "https://www.oiv.int/sites/default/files/2025-04/OIV-State_of_the_World_Vine-and-Wine-Sector-in-2024.pdf"
  },
  {
    "id": "global-shoes-made",
    "category": "fashion",
    "label": "have been made around the world",
    "rate": 757.345298755,
    "period": "second",
    "unit": "pairs of shoes",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "World Footwear Yearbook 2025",
    "sourceUrl": "https://www.worldfootwear.com/news/footwear-production-rebounds-in-2024/10835.html"
  },
  {
    "id": "china-shoes-made",
    "category": "fashion",
    "label": "China has made",
    "rate": 411.945141582,
    "period": "second",
    "unit": "pairs of shoes",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "World Footwear Yearbook 2025",
    "sourceUrl": "https://www.worldfootwear.com/news/footwear-production-rebounds-in-2024/10835.html"
  },
  {
    "id": "global-crops-harvested",
    "category": "food",
    "label": "fields around the world have yielded",
    "rate": 313.712069359,
    "period": "second",
    "unit": "tonnes of crops",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "FAO agricultural production statistics, 2023",
    "sourceUrl": "https://www.fao.org/statistics/highlights-archive/highlights-detail/agricultural-production-statistics-2010-2023/en"
  },
  {
    "id": "global-sugarcane-harvested",
    "category": "food",
    "label": "fields have yielded",
    "rate": 63.376175628,
    "period": "second",
    "unit": "tonnes of sugar cane",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "FAO agricultural production statistics, 2023",
    "sourceUrl": "https://www.fao.org/statistics/highlights-archive/highlights-detail/agricultural-production-statistics-2010-2023/en"
  },
  {
    "id": "global-fruit-vegetables-harvested",
    "category": "food",
    "label": "farms have harvested",
    "rate": 66.544984409,
    "period": "second",
    "unit": "tonnes of fruit and vegetables",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "FAO agricultural production statistics, 2023",
    "sourceUrl": "https://www.fao.org/statistics/highlights-archive/highlights-detail/agricultural-production-statistics-2010-2023/en"
  },
  {
    "id": "global-oil-crops-harvested",
    "category": "food",
    "label": "farms have harvested",
    "rate": 28.297462418,
    "period": "second",
    "unit": "tonnes of oil crops",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "FAO agricultural production statistics, 2023",
    "sourceUrl": "https://www.fao.org/statistics/highlights-archive/highlights-detail/agricultural-production-statistics-2010-2023/en"
  },
  {
    "id": "bananas-harvested",
    "category": "food",
    "label": "farms have harvested",
    "rate": 4.404644206,
    "period": "second",
    "unit": "tonnes of bananas",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "FAO agricultural production analytical brief, 2023",
    "sourceUrl": "https://openknowledge.fao.org/bitstreams/df90e6cf-4178-4361-97d4-5154a9213877/download"
  },
  {
    "id": "watermelons-harvested",
    "category": "food",
    "label": "farms have harvested",
    "rate": 3.32724922,
    "period": "second",
    "unit": "tonnes of watermelons",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "FAO agricultural production analytical brief, 2023",
    "sourceUrl": "https://openknowledge.fao.org/bitstreams/df90e6cf-4178-4361-97d4-5154a9213877/download"
  },
  {
    "id": "apples-harvested",
    "category": "food",
    "label": "farms have harvested",
    "rate": 3.073744518,
    "period": "second",
    "unit": "tonnes of apples",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "FAO agricultural production analytical brief, 2023",
    "sourceUrl": "https://openknowledge.fao.org/bitstreams/df90e6cf-4178-4361-97d4-5154a9213877/download"
  },
  {
    "id": "grapes-harvested",
    "category": "food",
    "label": "farms have harvested",
    "rate": 2.281542323,
    "period": "second",
    "unit": "tonnes of grapes",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "FAO agricultural production analytical brief, 2023",
    "sourceUrl": "https://openknowledge.fao.org/bitstreams/df90e6cf-4178-4361-97d4-5154a9213877/download"
  },
  {
    "id": "potatoes-harvested",
    "category": "food",
    "label": "farms have harvested",
    "rate": 12.136537633,
    "period": "second",
    "unit": "tonnes of potatoes",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "FAO agricultural production analytical brief, 2023",
    "sourceUrl": "https://openknowledge.fao.org/bitstreams/df90e6cf-4178-4361-97d4-5154a9213877/download"
  },
  {
    "id": "cassava-harvested",
    "category": "food",
    "label": "farms have harvested",
    "rate": 10.58382133,
    "period": "second",
    "unit": "tonnes of cassava",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "FAO agricultural production analytical brief, 2023",
    "sourceUrl": "https://openknowledge.fao.org/bitstreams/df90e6cf-4178-4361-97d4-5154a9213877/download"
  },
  {
    "id": "tomatoes-harvested",
    "category": "food",
    "label": "farms have harvested",
    "rate": 6.08411286,
    "period": "second",
    "unit": "tonnes of tomatoes",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "FAO agricultural production analytical brief, 2023",
    "sourceUrl": "https://openknowledge.fao.org/bitstreams/df90e6cf-4178-4361-97d4-5154a9213877/download"
  },
  {
    "id": "onions-harvested",
    "category": "food",
    "label": "farms have harvested",
    "rate": 3.517377747,
    "period": "second",
    "unit": "tonnes of onions",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "FAO agricultural production analytical brief, 2023",
    "sourceUrl": "https://openknowledge.fao.org/bitstreams/df90e6cf-4178-4361-97d4-5154a9213877/download"
  },
  {
    "id": "global-meat-produced",
    "category": "food",
    "label": "farms have produced",
    "rate": 11.851344842,
    "period": "second",
    "unit": "tonnes of meat",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "FAO agricultural production statistics, 2024",
    "sourceUrl": "https://www.fao.org/statistics/highlights-archive/highlights-detail/agricultural-production-statistics-2010-2024/en"
  },
  {
    "id": "maize-harvested",
    "category": "food",
    "label": "fields have yielded",
    "rate": 38.659467133,
    "period": "second",
    "unit": "tonnes of maize",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "FAO agricultural production analytical brief, 2024",
    "sourceUrl": "https://openknowledge.fao.org/bitstreams/23eaa328-ac5a-444e-ac62-80a636acd81f/download"
  },
  {
    "id": "shelter-animals-entering",
    "category": "animals",
    "label": "dogs and cats have entered U.S. shelters and rescues",
    "rate": 0.183790909,
    "period": "second",
    "unit": "animals",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "Shelter Animals Count, 2024 annual analysis",
    "sourceUrl": "https://www.shelteranimalscount.org/explore-the-data/statistics-2024/"
  },
  {
    "id": "shelter-dogs-entering",
    "category": "animals",
    "label": "dogs have entered U.S. shelters and rescues",
    "rate": 0.091895455,
    "period": "second",
    "unit": "dogs",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "Shelter Animals Count, 2024 annual analysis",
    "sourceUrl": "https://www.shelteranimalscount.org/explore-the-data/statistics-2024/"
  },
  {
    "id": "shelter-cats-entering",
    "category": "animals",
    "label": "cats have entered U.S. shelters and rescues",
    "rate": 0.091895455,
    "period": "second",
    "unit": "cats",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "Shelter Animals Count, 2024 annual analysis",
    "sourceUrl": "https://www.shelteranimalscount.org/explore-the-data/statistics-2024/"
  },
  {
    "id": "shelter-animals-adopted",
    "category": "animals",
    "label": "dogs and cats have found new homes",
    "rate": 0.132850502,
    "period": "second",
    "unit": "animals",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "Shelter Animals Count, 2024 annual analysis",
    "sourceUrl": "https://www.shelteranimalscount.org/explore-the-data/statistics-2024/"
  },
  {
    "id": "shelter-dogs-adopted",
    "category": "animals",
    "label": "shelter dogs have found new homes",
    "rate": 0.063376176,
    "period": "second",
    "unit": "dogs",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "Shelter Animals Count, 2024 annual analysis",
    "sourceUrl": "https://www.shelteranimalscount.org/explore-the-data/statistics-2024/"
  },
  {
    "id": "shelter-cats-adopted",
    "category": "animals",
    "label": "shelter cats have found new homes",
    "rate": 0.063376176,
    "period": "second",
    "unit": "cats",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "Shelter Animals Count, 2024 annual analysis",
    "sourceUrl": "https://www.shelteranimalscount.org/explore-the-data/statistics-2024/"
  },
  {
    "id": "fisheries-aquaculture-produced",
    "category": "animals",
    "label": "the world has produced",
    "rate": 7.0727812,
    "period": "second",
    "unit": "tonnes of fish and aquatic foods",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "FAO State of World Fisheries and Aquaculture 2024",
    "sourceUrl": "https://www.fao.org/newsroom/detail/fao-report-global-fisheries-and-aquaculture-production-reaches-a-new-record-high/en"
  },
  {
    "id": "aquatic-animals-produced",
    "category": "animals",
    "label": "the world has raised and caught",
    "rate": 5.874971481,
    "period": "second",
    "unit": "tonnes of aquatic animals",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "FAO State of World Fisheries and Aquaculture 2024",
    "sourceUrl": "https://www.fao.org/newsroom/detail/fao-report-global-fisheries-and-aquaculture-production-reaches-a-new-record-high/en"
  },
  {
    "id": "algae-produced",
    "category": "animals",
    "label": "the world has grown",
    "rate": 1.197809719,
    "period": "second",
    "unit": "tonnes of algae",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "FAO State of World Fisheries and Aquaculture 2024",
    "sourceUrl": "https://www.fao.org/newsroom/detail/fao-report-global-fisheries-and-aquaculture-production-reaches-a-new-record-high/en"
  },
  {
    "id": "aquaculture-produced",
    "category": "animals",
    "label": "fish farms have produced",
    "rate": 4.147970695,
    "period": "second",
    "unit": "tonnes of aquatic food",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "FAO State of World Fisheries and Aquaculture 2024",
    "sourceUrl": "https://www.fao.org/newsroom/detail/fao-report-global-fisheries-and-aquaculture-production-reaches-a-new-record-high/en"
  },
  {
    "id": "farmed-aquatic-animals",
    "category": "animals",
    "label": "fish farms have raised",
    "rate": 2.99135549,
    "period": "second",
    "unit": "tonnes of aquatic animals",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "FAO State of World Fisheries and Aquaculture 2024",
    "sourceUrl": "https://www.fao.org/newsroom/detail/fao-report-global-fisheries-and-aquaculture-production-reaches-a-new-record-high/en"
  },
  {
    "id": "wild-caught-fish",
    "category": "animals",
    "label": "fishers have caught",
    "rate": 2.924810505,
    "period": "second",
    "unit": "tonnes of aquatic animals",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "FAO State of World Fisheries and Aquaculture 2024",
    "sourceUrl": "https://www.fao.org/newsroom/detail/fao-report-global-fisheries-and-aquaculture-production-reaches-a-new-record-high/en"
  },
  {
    "id": "ebird-observations",
    "category": "animals",
    "label": "birdwatchers have shared",
    "rate": 8.492407534,
    "period": "second",
    "unit": "bird observations",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "eBird 2024 year in review",
    "sourceUrl": "https://ebird.org/news/2024-year-in-review"
  },
  {
    "id": "new-ebirders",
    "category": "animals",
    "label": "new birdwatchers have joined eBird",
    "rate": 0.003865947,
    "period": "second",
    "unit": "people",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "eBird 2024 year in review",
    "sourceUrl": "https://ebird.org/news/2024-year-in-review",
    "minimumElapsedSeconds": 3600
  },
  {
    "id": "ebird-research-papers",
    "category": "science",
    "label": "new papers have used eBird data",
    "rate": 0.000007859,
    "period": "second",
    "unit": "research papers",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "eBird 2024 year in review",
    "sourceUrl": "https://ebird.org/news/2024-year-in-review",
    "minimumElapsedSeconds": 604800
  },
  {
    "id": "new-species-described",
    "category": "science",
    "label": "California Academy scientists have described",
    "rate": 0.000004373,
    "period": "second",
    "unit": "new species",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "California Academy of Sciences, 2024 species report",
    "sourceUrl": "https://www.calacademy.org/press/releases/california-academy-of-sciences-describes-138-new-species-in-2024",
    "minimumElapsedSeconds": 604800
  },
  {
    "id": "patent-applications",
    "category": "science",
    "label": "inventors have filed",
    "rate": 0.117245925,
    "period": "second",
    "unit": "patent applications",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "WIPO World Intellectual Property Indicators, 2024",
    "sourceUrl": "https://www.wipo.int/en/web/ip-statistics/w/news/2025/world-intellectual-property-indicators-global-patent-and-design-filings-reach-new-records-in-2024-trademarks-flat"
  },
  {
    "id": "trademark-applications",
    "category": "science",
    "label": "creators have filed",
    "rate": 0.481658935,
    "period": "second",
    "unit": "trademark applications",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "WIPO World Intellectual Property Indicators, 2024",
    "sourceUrl": "https://www.wipo.int/en/web/ip-statistics/w/news/2025/world-intellectual-property-indicators-global-patent-and-design-filings-reach-new-records-in-2024-trademarks-flat"
  },
  {
    "id": "industrial-design-applications",
    "category": "science",
    "label": "designers have filed",
    "rate": 0.050700941,
    "period": "second",
    "unit": "industrial design applications",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "WIPO World Intellectual Property Indicators, 2024",
    "sourceUrl": "https://www.wipo.int/en/web/ip-statistics/w/news/2025/world-intellectual-property-indicators-global-patent-and-design-filings-reach-new-records-in-2024-trademarks-flat"
  },
  {
    "id": "orbital-launches",
    "category": "science",
    "label": "have reached orbit",
    "rate": 0.000008207,
    "period": "second",
    "unit": "rocket launches",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "BryceTech Global Space Launch Activity 2024",
    "sourceUrl": "https://brycetech.com/reports/report-documents/global-space-launch-activity-2024/",
    "minimumElapsedSeconds": 604800
  },
  {
    "id": "spacecraft-deployed",
    "category": "science",
    "label": "new spacecraft have been deployed",
    "rate": 0.000091895,
    "period": "second",
    "unit": "spacecraft",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "BryceTech Global Space Launch Activity 2024",
    "sourceUrl": "https://brycetech.com/reports/report-documents/global-space-launch-activity-2024/",
    "minimumElapsedSeconds": 21600
  },
  {
    "id": "youtube-videos-uploaded",
    "category": "social",
    "label": "creators have uploaded",
    "rate": 231.481481481,
    "period": "second",
    "unit": "videos to YouTube",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "YouTube press facts",
    "sourceUrl": "https://blog.youtube/press/"
  },
  {
    "id": "youtube-shorts-views",
    "category": "social",
    "label": "have been watched",
    "rate": 2314814.814814815,
    "period": "second",
    "unit": "YouTube Shorts views",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "YouTube press facts",
    "sourceUrl": "https://blog.youtube/press/"
  },
  {
    "id": "snapchat-snaps-created",
    "category": "social",
    "label": "Snapchatters have created",
    "rate": 63657.407407407,
    "period": "second",
    "unit": "Snaps",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "Snap 2025 year in review",
    "sourceUrl": "https://newsroom.snap.com/2trillion-snaps-in-2025"
  },
  {
    "id": "snapchat-talk-minutes",
    "category": "social",
    "label": "Snapchatters have spent",
    "rate": 19675.925925926,
    "period": "second",
    "unit": "minutes talking",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "Snapchat Generation Report",
    "sourceUrl": "https://newsroom.snap.com/snapchat-generation-report"
  },
  {
    "id": "snapchat-ar-users",
    "category": "social",
    "label": "have used Snapchat augmented reality",
    "rate": 4050.925925926,
    "period": "second",
    "unit": "Snapchatters",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "Snap newsroom facts",
    "sourceUrl": "https://newsroom.snap.com/"
  },
  {
    "id": "meta-messages-sent",
    "category": "social",
    "label": "people have sent",
    "rate": 1157407.407407407,
    "period": "second",
    "unit": "messages on Meta apps",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "Meta messaging announcement",
    "sourceUrl": "https://about.fb.com/news/2020/09/new-messaging-features-for-instagram/"
  },
  {
    "id": "reddit-content-created",
    "category": "social",
    "label": "Redditors have shared",
    "rate": 377.415458937,
    "period": "second",
    "unit": "posts and comments",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "Reddit H2 2024 transparency report",
    "sourceUrl": "https://redditinc.com/policies/transparency-report-july-to-december-2024"
  },
  {
    "id": "tiktok-videos-posted",
    "category": "social",
    "label": "creators have posted",
    "rate": 393.518518519,
    "period": "second",
    "unit": "TikTok videos",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "Harvard Business School music-demand study",
    "sourceUrl": "https://www.hbs.edu/ris/download.aspx?name=25-014.pdf"
  },
  {
    "id": "live-nation-fans",
    "category": "culture",
    "label": "Live Nation shows have welcomed",
    "rate": 4.753213172,
    "period": "second",
    "unit": "fans",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "Live Nation 2024 annual report",
    "sourceUrl": "https://investors.livenationentertainment.com/sec-filings/annual-reports/content/0001193125-25-094946/0001193125-25-094946.pdf"
  },
  {
    "id": "live-nation-venue-fans",
    "category": "culture",
    "label": "Live Nation venues and festivals have welcomed",
    "rate": 1.901285269,
    "period": "second",
    "unit": "fans",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "Live Nation 2024 annual report",
    "sourceUrl": "https://investors.livenationentertainment.com/sec-filings/annual-reports/content/0001193125-25-094946/0001193125-25-094946.pdf"
  },
  {
    "id": "live-nation-shows",
    "category": "culture",
    "label": "Live Nation has put on",
    "rate": 0.001584404,
    "period": "second",
    "unit": "shows",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "Live Nation 2024 annual report",
    "sourceUrl": "https://investors.livenationentertainment.com/sec-filings/annual-reports/content/0001193125-25-094946/0001193125-25-094946.pdf",
    "minimumElapsedSeconds": 1200
  },
  {
    "id": "international-tourists",
    "category": "travel",
    "label": "have travelled internationally",
    "rate": 44.36332294,
    "period": "second",
    "unit": "international tourists",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "UN Tourism 2024 World Tourism Barometer",
    "sourceUrl": "https://www.untourism.int/news/international-tourism-recovers-pre-pandemic-levels-in-2024"
  },
  {
    "id": "tourism-exports",
    "category": "economy",
    "label": "international tourism has generated",
    "rate": 60207.366846655,
    "period": "second",
    "unit": "dollars in exports",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "UN Tourism 2024 World Tourism Barometer",
    "sourceUrl": "https://www.untourism.int/news/international-tourism-recovers-pre-pandemic-levels-in-2024"
  },
  {
    "id": "tourism-gdp",
    "category": "economy",
    "label": "travel and tourism have added",
    "rate": 345400.157172916,
    "period": "second",
    "unit": "dollars to the global economy",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "World Bank tourism facts",
    "sourceUrl": "https://www.worldbank.org/ext/en/topic/tourism"
  },
  {
    "id": "foreign-exchange-trading",
    "category": "economy",
    "label": "foreign-exchange markets have traded",
    "rate": 111111111.1111111,
    "period": "second",
    "unit": "dollars",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "BIS 2025 Triennial FX Survey",
    "sourceUrl": "https://www.bis.org/statistics/rpfx25_fx.htm"
  },
  {
    "id": "global-trade",
    "category": "economy",
    "label": "goods and services have crossed borders worth",
    "rate": 1045706.897862955,
    "period": "second",
    "unit": "dollars",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "UNCTAD Global Trade Update, 2024",
    "sourceUrl": "https://unctad.org/news/global-trade-hits-record-33-trillion-2024-driven-services-and-developing-economies"
  },
  {
    "id": "remittances",
    "category": "economy",
    "label": "people have sent home",
    "rate": 21706.34015261,
    "period": "second",
    "unit": "dollars in remittances",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "World Bank 2024 remittance estimates",
    "sourceUrl": "https://blogs.worldbank.org/en/peoplemove/in-2024--remittance-flows-to-low--and-middle-income-countries-ar"
  },
  {
    "id": "global-games-revenue",
    "category": "economy",
    "label": "players have spent",
    "rate": 5982.710979289,
    "period": "second",
    "unit": "dollars on games",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "Newzoo Global Games Market Report 2025",
    "sourceUrl": "https://newzoo.com/articles/global-games-market-189-billion-2025/"
  },
  {
    "id": "stablecoin-transactions",
    "category": "crypto",
    "label": "stablecoins have completed",
    "rate": 139.906389906,
    "period": "second",
    "unit": "transactions",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "a16z State of Crypto 2024",
    "sourceUrl": "https://a16zcrypto.com/posts/article/state-of-crypto-report-2024/"
  }
];
