export default [
  {
    "id": "solar-system-galactic-distance",
    "category": "cosmic",
    "label": "kilometers traveled by the Solar System through the Milky Way",
    "rate": 220,
    "period": "second",
    "decimalPlaces": 0,
    "format": "number",
    "sourceLabel": null,
    "sourceUrl": null
  },
  {
    "id": "earth-orbital-distance",
    "category": "cosmic",
    "label": "kilometers traveled by Earth around the Sun",
    "rate": 29.78,
    "period": "second",
    "decimalPlaces": 0,
    "format": "number",
    "sourceLabel": null,
    "sourceUrl": null
  },
  {
    "id": "moon-orbital-distance",
    "category": "cosmic",
    "label": "kilometers traveled by the Moon around Earth",
    "rate": 1.022,
    "period": "second",
    "decimalPlaces": 0,
    "format": "number",
    "sourceLabel": null,
    "sourceUrl": null
  },
  {
    "id": "iss-distance",
    "category": "cosmic",
    "label": "kilometers traveled by the International Space Station above Earth",
    "rate": 7.66,
    "period": "second",
    "decimalPlaces": 0,
    "format": "number",
    "sourceLabel": null,
    "sourceUrl": null
  },
  {
    "id": "equator-distance",
    "category": "cosmic",
    "label": "kilometers traveled by a point on Earth's equator",
    "rate": 0.465,
    "period": "second",
    "decimalPlaces": 0,
    "format": "number",
    "sourceLabel": null,
    "sourceUrl": null
  },
  {
    "id": "light-speed-frontier",
    "category": "cosmic",
    "label": "kilometers a light-speed signal could have traveled from Earth",
    "rate": 299792.458,
    "period": "second",
    "decimalPlaces": 0,
    "format": "number",
    "sourceLabel": null,
    "sourceUrl": null
  },
  {
    "id": "solar-mass-converted",
    "category": "cosmic",
    "label": "tons of the Sun converted into light",
    "rate": 4260000,
    "period": "second",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": null,
    "sourceUrl": null
  },
  {
    "id": "solar-energy-received",
    "category": "cosmic",
    "label": "petajoules of sunlight received by Earth",
    "rate": 174,
    "period": "second",
    "decimalPlaces": 0,
    "format": "number",
    "sourceLabel": null,
    "sourceUrl": null
  },
  {
    "id": "solar-neutrinos",
    "category": "cosmic",
    "label": "solar neutrinos passing through every square centimeter of you",
    "rate": 65000000000,
    "period": "second",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": null,
    "sourceUrl": null
  },
  {
    "id": "cosmic-dust",
    "category": "cosmic",
    "label": "kilograms of cosmic dust settled on Earth",
    "rate": 0.6,
    "period": "second",
    "decimalPlaces": 1,
    "format": "number",
    "sourceLabel": null,
    "sourceUrl": null
  },
  {
    "id": "lightning-flashes",
    "category": "planetary",
    "label": "lightning strikes on Earth",
    "rate": 44,
    "period": "second",
    "decimalPlaces": 0,
    "format": "number",
    "sourceLabel": null,
    "sourceUrl": null
  },
  {
    "id": "water-evaporated",
    "category": "planetary",
    "label": "cubic meters of water evaporated into the atmosphere",
    "rate": 16000000,
    "period": "second",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": null,
    "sourceUrl": null
  },
  {
    "id": "co2-emitted",
    "category": "planetary",
    "label": "tons of carbon dioxide emitted",
    "rate": 1200,
    "period": "second",
    "decimalPlaces": 0,
    "format": "number",
    "sourceLabel": null,
    "sourceUrl": null
  },
  {
    "id": "oxygen-released",
    "category": "planetary",
    "label": "tons of oxygen released by photosynthesis",
    "rate": 3000,
    "period": "second",
    "decimalPlaces": 0,
    "format": "number",
    "sourceLabel": null,
    "sourceUrl": null
  },
  {
    "id": "forest-cleared",
    "category": "planetary",
    "label": "hectares of forest cleared",
    "rate": 0.32,
    "period": "second",
    "decimalPlaces": 2,
    "format": "number",
    "sourceLabel": null,
    "sourceUrl": null
  },
  {
    "id": "plastic-produced",
    "category": "materials",
    "label": "tons of plastic produced",
    "rate": 12.7,
    "period": "second",
    "decimalPlaces": 0,
    "format": "number",
    "sourceLabel": null,
    "sourceUrl": null
  },
  {
    "id": "cement-produced",
    "category": "materials",
    "label": "tons of cement produced",
    "rate": 140,
    "period": "second",
    "decimalPlaces": 0,
    "format": "number",
    "sourceLabel": null,
    "sourceUrl": null
  },
  {
    "id": "energy-used",
    "category": "materials",
    "label": "terajoules of energy used worldwide",
    "rate": 19,
    "period": "second",
    "decimalPlaces": 0,
    "format": "number",
    "sourceLabel": null,
    "sourceUrl": null
  },
  {
    "id": "freshwater-withdrawn",
    "category": "materials",
    "label": "cubic meters of freshwater withdrawn for human use",
    "rate": 130000,
    "period": "second",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": null,
    "sourceUrl": null
  },
  {
    "id": "oil-used",
    "category": "materials",
    "label": "liters of oil used worldwide",
    "rate": 184000,
    "period": "second",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": null,
    "sourceUrl": null
  },
  {
    "id": "births",
    "category": "human",
    "label": "people born worldwide",
    "rate": 4.2,
    "period": "second",
    "decimalPlaces": 0,
    "format": "number",
    "sourceLabel": null,
    "sourceUrl": null
  },
  {
    "id": "deaths",
    "category": "human",
    "label": "people who died worldwide",
    "rate": 2,
    "period": "second",
    "decimalPlaces": 0,
    "format": "number",
    "sourceLabel": null,
    "sourceUrl": null
  },
  {
    "id": "human-heartbeats",
    "category": "human",
    "label": "human heartbeats",
    "rate": 9300000000,
    "period": "second",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": null,
    "sourceUrl": null
  },
  {
    "id": "human-breaths",
    "category": "human",
    "label": "human breaths taken",
    "rate": 1600000000,
    "period": "second",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": null,
    "sourceUrl": null
  },
  {
    "id": "meals-eaten",
    "category": "human",
    "label": "meals eaten worldwide",
    "rate": 277778,
    "period": "second",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": null,
    "sourceUrl": null
  },
  {
    "id": "words-spoken",
    "category": "human",
    "label": "words spoken worldwide",
    "rate": 1500000000,
    "period": "second",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": null,
    "sourceUrl": null
  },
  {
    "id": "coffee-consumed",
    "category": "human",
    "label": "cups of coffee drunk",
    "rate": 26000,
    "period": "second",
    "decimalPlaces": 0,
    "format": "number",
    "sourceLabel": null,
    "sourceUrl": null
  },
  {
    "id": "eggs-laid",
    "category": "human",
    "label": "eggs laid by chickens",
    "rate": 47000,
    "period": "second",
    "decimalPlaces": 0,
    "format": "number",
    "sourceLabel": null,
    "sourceUrl": null
  },
  {
    "id": "air-passengers",
    "category": "infrastructure",
    "label": "passengers carried by aircraft",
    "rate": 150,
    "period": "second",
    "decimalPlaces": 0,
    "format": "number",
    "sourceLabel": null,
    "sourceUrl": null
  },
  {
    "id": "parcels-shipped",
    "category": "infrastructure",
    "label": "parcels starting a journey",
    "rate": 5000,
    "period": "second",
    "decimalPlaces": 0,
    "format": "number",
    "sourceLabel": null,
    "sourceUrl": null
  },
  {
    "id": "emails-sent",
    "category": "network",
    "label": "emails sent",
    "rate": 3500000,
    "period": "second",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": null,
    "sourceUrl": null
  },
  {
    "id": "web-searches",
    "category": "network",
    "label": "web searches",
    "rate": 100000,
    "period": "second",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": null,
    "sourceUrl": null
  },
  {
    "id": "text-messages",
    "category": "network",
    "label": "text messages exchanged",
    "rate": 250000,
    "period": "second",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": null,
    "sourceUrl": null
  },
  {
    "id": "photos-taken",
    "category": "network",
    "label": "photos taken",
    "rate": 63000,
    "period": "second",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": null,
    "sourceUrl": null
  },
  {
    "id": "video-uploaded",
    "category": "network",
    "label": "hours of video uploaded",
    "rate": 8.3,
    "period": "second",
    "decimalPlaces": 0,
    "format": "number",
    "sourceLabel": null,
    "sourceUrl": null
  },
  {
    "id": "songs-streamed",
    "category": "culture",
    "label": "songs streamed",
    "rate": 60000,
    "period": "second",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": null,
    "sourceUrl": null
  },
  {
    "id": "online-payments",
    "category": "culture",
    "label": "online payments processed",
    "rate": 50000,
    "period": "second",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": null,
    "sourceUrl": null
  },
  {
    "id": "wikipedia-edits",
    "category": "culture",
    "label": "Wikipedia edits",
    "rate": 2,
    "period": "second",
    "decimalPlaces": 0,
    "format": "number",
    "sourceLabel": null,
    "sourceUrl": null
  },
  {
    "id": "grain-harvested",
    "category": "food",
    "label": "kilograms of grain harvested",
    "rate": 90000,
    "period": "second",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": null,
    "sourceUrl": null
  },
  {
    "id": "milk-produced",
    "category": "food",
    "label": "liters of milk produced",
    "rate": 28500,
    "period": "second",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": null,
    "sourceUrl": null
  },
  {
    "id": "crayola-crayons",
    "category": "play",
    "label": "Crayola crayons made",
    "rate": 95.064263442,
    "period": "second",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "Crayola annual production FAQ",
    "sourceUrl": "https://www.crayola.com/faqs/how-many-crayola-products-do-you-make-per-year-faq"
  },
  {
    "id": "crayola-colored-pencils",
    "category": "play",
    "label": "Crayola colored pencils made",
    "rate": 19.012852688,
    "period": "second",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "Crayola annual production FAQ",
    "sourceUrl": "https://www.crayola.com/faqs/how-many-crayola-products-do-you-make-per-year-faq"
  },
  {
    "id": "crayola-markers",
    "category": "play",
    "label": "Crayola markers made",
    "rate": 14.734960834,
    "period": "second",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "Crayola annual production FAQ",
    "sourceUrl": "https://www.crayola.com/faqs/how-many-crayola-products-do-you-make-per-year-faq"
  },
  {
    "id": "crayola-chalk",
    "category": "play",
    "label": "sticks of Crayola chalk made",
    "rate": 3.48568966,
    "period": "second",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "Crayola annual production FAQ",
    "sourceUrl": "https://www.crayola.com/faqs/how-many-crayola-products-do-you-make-per-year-faq"
  },
  {
    "id": "crayola-silly-putty-eggs",
    "category": "play",
    "label": "Silly Putty eggs made by Crayola",
    "rate": 0.28519279,
    "period": "second",
    "decimalPlaces": 0,
    "format": "number",
    "sourceLabel": "Crayola annual production FAQ",
    "sourceUrl": "https://www.crayola.com/faqs/how-many-crayola-products-do-you-make-per-year-faq"
  },
  {
    "id": "crayola-paint-jars",
    "category": "play",
    "label": "jars of Crayola paint filled",
    "rate": 0.047532132,
    "period": "second",
    "decimalPlaces": 0,
    "format": "number",
    "sourceLabel": "Crayola annual production FAQ",
    "sourceUrl": "https://www.crayola.com/faqs/how-many-crayola-products-do-you-make-per-year-faq"
  },
  {
    "id": "ben-jerrys-pints",
    "category": "food",
    "label": "pints of ice cream churned at Ben & Jerry's Waterbury factory",
    "rate": 4.050925926,
    "period": "second",
    "decimalPlaces": 0,
    "format": "number",
    "sourceLabel": "Ben & Jerry’s Waterbury factory tour",
    "sourceUrl": "https://www.benjerry.com/about-us/factory-tours"
  },
  {
    "id": "greeting-cards-purchased",
    "category": "celebration",
    "label": "greeting cards bought in the U.S.",
    "rate": 205.972570791,
    "period": "second",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "Hallmark, citing the Greeting Card Association",
    "sourceUrl": "https://corporate.hallmark.com/hallmark-news/greetings/"
  },
  {
    "id": "public-library-visits",
    "category": "culture",
    "label": "visits to U.S. public libraries",
    "rate": 25.350470251,
    "period": "second",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "IMLS 2023 public library survey data",
    "sourceUrl": "https://content.govdelivery.com/accounts/USIMLS/bulletins/3f09e4a"
  },
  {
    "id": "pokemon-cards-printed",
    "category": "games",
    "label": "Pokémon cards printed",
    "rate": 316.88087814,
    "period": "second",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "IGN reporting Pokémon Company card production",
    "sourceUrl": "https://www.ign.com/articles/10-billion-pokemon-cards-were-printed-last-year-and-it-still-wasnt-enough-to-stop-shortages-and-scalping"
  },
  {
    "id": "lego-kids-reached",
    "category": "play",
    "label": "children reached by LEGO play initiatives",
    "rate": 0.380257054,
    "period": "second",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "LEGO Group Annual Report 2024",
    "sourceUrl": "https://www.lego.com/cdn/cs/aboutus/assets/blt1cdf90a38318ef56/the_LEGO_Group_Annual_Report_2024.pdf"
  },
  {
    "id": "lego-play-downloads",
    "category": "play",
    "label": "downloads of the LEGO Play app",
    "rate": 0.158440439,
    "period": "second",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "LEGO Group Annual Report 2024",
    "sourceUrl": "https://www.lego.com/cdn/cs/aboutus/assets/blt1cdf90a38318ef56/the_LEGO_Group_Annual_Report_2024.pdf"
  },
  {
    "id": "ps5-consoles-shipped",
    "category": "games",
    "label": "PlayStation 5 consoles shipped",
    "rate": 0.586229625,
    "period": "second",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "Sony Interactive Entertainment FY2024 sales data",
    "sourceUrl": "https://sonyinteractive.com/en/our-company/business-data-sales/"
  },
  {
    "id": "playstation-games-sold",
    "category": "games",
    "label": "PlayStation game copies shipped",
    "rate": 9.610997034,
    "period": "second",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "Sony Interactive Entertainment FY2024 sales data",
    "sourceUrl": "https://sonyinteractive.com/en/our-company/business-data-sales/"
  },
  {
    "id": "switch-consoles-sold",
    "category": "games",
    "label": "Nintendo Switch consoles sold",
    "rate": 0.497502979,
    "period": "second",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "Nintendo FY2024 financial results",
    "sourceUrl": "https://www.nintendo.co.jp/ir/pdf/2024/240507e.pdf"
  },
  {
    "id": "switch-games-sold",
    "category": "games",
    "label": "Nintendo Switch games sold",
    "rate": 5.195261997,
    "period": "second",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "Nintendo FY2024 financial results",
    "sourceUrl": "https://www.nintendo.co.jp/ir/pdf/2024/240507e.pdf"
  },
  {
    "id": "uber-trips",
    "category": "travel",
    "label": "Uber trips completed",
    "rate": 354.906583517,
    "period": "second",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "Uber full-year 2024 results",
    "sourceUrl": "https://investor.uber.com/news-events/news/press-release-details/2025/Uber-Announces-Results-for-Fourth-Quarter-and-Full-Year-2024/default.aspx"
  },
  {
    "id": "lyft-rides",
    "category": "travel",
    "label": "Lyft rides taken",
    "rate": 26.23773671,
    "period": "second",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "Lyft full-year 2024 results",
    "sourceUrl": "https://investor.lyft.com/news-events-presentations/press-releases/detail/103/lyft-reports-record-q4-and-full-year-2024-results"
  },
  {
    "id": "airbnb-bookings",
    "category": "travel",
    "label": "Airbnb bookings made",
    "rate": 15.558851117,
    "period": "second",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "Airbnb Q4 and full-year 2024 results",
    "sourceUrl": "https://news.airbnb.com/airbnb-q4-2024-financial-results/"
  },
  {
    "id": "amtrak-trips",
    "category": "travel",
    "label": "Amtrak trips taken",
    "rate": 1.03936928,
    "period": "second",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "Amtrak FY2024 ridership release",
    "sourceUrl": "https://media.amtrak.com/2024/12/amtrak-sets-all-time-ridership-record-in-fiscal-year-2024/"
  },
  {
    "id": "tsa-screenings",
    "category": "travel",
    "label": "travelers passing through U.S. airport security",
    "rate": 28.646031384,
    "period": "second",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "TSA 2024 checkpoint travel numbers",
    "sourceUrl": "https://www.tsa.gov/travel/passenger-volumes"
  },
  {
    "id": "nhl-attendance",
    "category": "sports",
    "label": "NHL arena seats filled by hockey fans",
    "rate": 0.729284166,
    "period": "second",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "NHL 2024–25 regular-season attendance",
    "sourceUrl": "https://www.nhl.com/news/nhl-sets-regular-season-attendance-record-in-2024-2025"
  },
  {
    "id": "usps-mail-pieces",
    "category": "delivery",
    "label": "U.S. mail pieces handled",
    "rate": 3571.247496641,
    "period": "second",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "USPS FY2024 Annual Report",
    "sourceUrl": "https://about.usps.com/what/financials/annual-reports/fy2024.pdf"
  },
  {
    "id": "ups-packages",
    "category": "delivery",
    "label": "UPS packages delivered",
    "rate": 167.946865414,
    "period": "second",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "UPS 2024 Annual Report",
    "sourceUrl": "https://about.ups.com/us/en/our-company/annual-report.html"
  },
  {
    "id": "recorded-music-revenue",
    "category": "music",
    "label": "dollars in U.S. recorded-music revenue",
    "rate": 560.879154308,
    "period": "second",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "RIAA 2024 year-end revenue report",
    "sourceUrl": "https://www.riaa.com/reports/2024-riaa-year-end-revenue-report/"
  },
  {
    "id": "nyc-subway-rides",
    "category": "city",
    "label": "New York City subway rides",
    "rate": 37.867264938,
    "period": "second",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "MTA 2024 ridership statistics",
    "sourceUrl": "https://metrics.mta.info/?subway"
  },
  {
    "id": "nyc-bus-rides",
    "category": "city",
    "label": "New York City bus rides",
    "rate": 18.379090932,
    "period": "second",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "MTA 2024 ridership statistics",
    "sourceUrl": "https://metrics.mta.info/?subway"
  },
  {
    "id": "national-park-visits",
    "category": "parks",
    "label": "visitors to U.S. national parks",
    "rate": 10.516115231,
    "period": "second",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "National Park Service 2024 visitation data",
    "sourceUrl": "https://www.nps.gov/aboutus/visitation-numbers.htm"
  },
  {
    "id": "great-smoky-mountains-visits",
    "category": "parks",
    "label": "visitors to Great Smoky Mountains",
    "rate": 0.386335906,
    "period": "second",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "National Park Service 2024 visitation data",
    "sourceUrl": "https://www.nps.gov/aboutus/visitation-numbers.htm"
  },
  {
    "id": "zion-visits",
    "category": "parks",
    "label": "visitors to Zion National Park",
    "rate": 0.156748042,
    "period": "second",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "National Park Service 2024 visitation data",
    "sourceUrl": "https://www.nps.gov/aboutus/visitation-numbers.htm"
  },
  {
    "id": "grand-canyon-visits",
    "category": "parks",
    "label": "visitors to the Grand Canyon",
    "rate": 0.155900132,
    "period": "second",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "National Park Service 2024 visitation data",
    "sourceUrl": "https://www.nps.gov/aboutus/visitation-numbers.htm"
  },
  {
    "id": "yellowstone-visits",
    "category": "parks",
    "label": "visitors to Yellowstone",
    "rate": 0.150332345,
    "period": "second",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "National Park Service 2024 visitation data",
    "sourceUrl": "https://www.nps.gov/aboutus/visitation-numbers.htm"
  },
  {
    "id": "rocky-mountain-visits",
    "category": "parks",
    "label": "visitors to Rocky Mountain National Park",
    "rate": 0.131643376,
    "period": "second",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "National Park Service 2024 visitation data",
    "sourceUrl": "https://www.nps.gov/aboutus/visitation-numbers.htm"
  },
  {
    "id": "yosemite-visits",
    "category": "parks",
    "label": "visitors to Yosemite",
    "rate": 0.130591458,
    "period": "second",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "National Park Service 2024 visitation data",
    "sourceUrl": "https://www.nps.gov/aboutus/visitation-numbers.htm"
  },
  {
    "id": "mlb-attendance",
    "category": "sports",
    "label": "MLB stadium seats filled by baseball fans",
    "rate": 2.260893287,
    "period": "second",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "MLB 2024 attendance release",
    "sourceUrl": "https://www.mlb.com/press-release/press-release-mlb-finishes-2024-season-with-highest-attendance-in-seven-years"
  },
  {
    "id": "nba-attendance",
    "category": "sports",
    "label": "NBA arena seats filled by basketball fans",
    "rate": 0.714202538,
    "period": "second",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "NBA 2023–24 regular-season attendance release",
    "sourceUrl": "https://www.nba.com/news/nba-sets-all-time-record-for-attendance-and-sellouts-during-2023-24-regular-season"
  },
  {
    "id": "acadia-visits",
    "category": "parks",
    "label": "visitors to Acadia",
    "rate": 0.125537462,
    "period": "second",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "National Park Service 2024 visitation data",
    "sourceUrl": "https://www.nps.gov/aboutus/visitation-numbers.htm"
  },
  {
    "id": "grand-teton-visits",
    "category": "parks",
    "label": "visitors to Grand Teton",
    "rate": 0.114971417,
    "period": "second",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "National Park Service 2024 visitation data",
    "sourceUrl": "https://www.nps.gov/aboutus/visitation-numbers.htm"
  },
  {
    "id": "olympic-visits",
    "category": "parks",
    "label": "visitors to Olympic National Park",
    "rate": 0.117793083,
    "period": "second",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "National Park Service 2024 visitation data",
    "sourceUrl": "https://www.nps.gov/aboutus/visitation-numbers.htm"
  },
  {
    "id": "coca-cola-servings",
    "category": "food",
    "label": "Coca-Cola servings enjoyed",
    "rate": 25462.962962963,
    "period": "second",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "The Coca-Cola Company fact sheet",
    "sourceUrl": "https://www.coca-colacompany.com/about-us"
  },
  {
    "id": "mcdonalds-customers",
    "category": "food",
    "label": "customers served by McDonald’s",
    "rate": 729.166666667,
    "period": "second",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "McDonald’s company profile",
    "sourceUrl": "https://corporate.mcdonalds.com/corpmcd/our-company/who-we-are.html"
  },
  {
    "id": "nescafe-cups",
    "category": "food",
    "label": "cups of Nescafé enjoyed",
    "rate": 6000,
    "period": "second",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "Nestlé Nescafé announcement",
    "sourceUrl": "https://www.nestle.com/media/news/nescafe-ice-roast-coffee-launch"
  },
  {
    "id": "guinness-glasses",
    "category": "food",
    "label": "glasses of Guinness enjoyed",
    "rate": 115.740740741,
    "period": "second",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "Guinness FAQ",
    "sourceUrl": "https://www.guinness.com/en-us/frequently-asked-questions"
  },
  {
    "id": "walmart-customer-visits",
    "category": "commerce",
    "label": "visits to Walmart stores",
    "rate": 462.962962963,
    "period": "second",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "Walmart company facts",
    "sourceUrl": "https://corporate.walmart.com/about"
  },
  {
    "id": "walmart-items-moved",
    "category": "commerce",
    "label": "items moved by Walmart’s supply chain",
    "rate": 3168.808781403,
    "period": "second",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "Walmart company facts",
    "sourceUrl": "https://corporate.walmart.com/about"
  },
  {
    "id": "pepsico-servings",
    "category": "food",
    "label": "PepsiCo product servings enjoyed",
    "rate": 11574.074074074,
    "period": "second",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "PepsiCo company facts",
    "sourceUrl": "https://www.pepsico.com/about"
  },
  {
    "id": "unilever-product-users",
    "category": "personal-care",
    "label": "people using Unilever products",
    "rate": 42824.074074074,
    "period": "second",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "Unilever brand facts",
    "sourceUrl": "https://www.unilever.com/brands/"
  },
  {
    "id": "oreo-cookies-made",
    "category": "food",
    "label": "Oreo cookies made",
    "rate": 1267.523512561,
    "period": "second",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "Mondelēz Oreo facts",
    "sourceUrl": "https://www.mondelezinternational.com/News/Oreo-Little-Known-Facts/"
  },
  {
    "id": "hershey-kisses-made",
    "category": "food",
    "label": "Hershey’s Kisses made in West Hershey",
    "rate": 810.185185185,
    "period": "second",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "The Hershey Company plant facts",
    "sourceUrl": "https://www.thehersheycompany.com/en_us/home/about-us/the-company/plant-locations.html"
  },
  {
    "id": "ikea-food-balls-sold",
    "category": "food",
    "label": "IKEA food balls sold",
    "rate": 44.36332294,
    "period": "second",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "IKEA’s 40 years of meatballs",
    "sourceUrl": "https://www.ikea.com/global/en/stories/our-roots/meatball-40-years-251024/"
  },
  {
    "id": "bic-products-made",
    "category": "everyday",
    "label": "BIC products made",
    "rate": 274.305555556,
    "period": "second",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "BIC creations and innovations",
    "sourceUrl": "https://corporate.bic.com/en-us/group/our-creations"
  },
  {
    "id": "hot-wheels-sold",
    "category": "play",
    "label": "Hot Wheels cars sold",
    "rate": 16.5,
    "period": "second",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "PLAION press release quoting Hot Wheels figures",
    "sourceUrl": "https://press.plaion.com/-Hot-Wheels-Unleashed-Sold-One-Million-Copies-Worldwide"
  },
  {
    "id": "lego-bricks-made",
    "category": "play",
    "label": "LEGO bricks made",
    "rate": 1140.771161305,
    "period": "second",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "LEGOLAND Discovery Center LEGO facts",
    "sourceUrl": "https://www.legolanddiscoverycenter.com/michigan/post/lego-facts/"
  },
  {
    "id": "tesla-vehicles-made",
    "category": "vehicles",
    "label": "Tesla vehicles made",
    "rate": 0.056197018,
    "period": "second",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "Tesla 2024 production and deliveries",
    "sourceUrl": "https://ir.tesla.com/press-release/tesla-fourth-quarter-2024-production-deliveries-and-deployments"
  },
  {
    "id": "tesla-vehicles-delivered",
    "category": "vehicles",
    "label": "Tesla vehicles delivered",
    "rate": 0.056697151,
    "period": "second",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "Tesla 2024 production and deliveries",
    "sourceUrl": "https://ir.tesla.com/press-release/tesla-fourth-quarter-2024-production-deliveries-and-deployments"
  },
  {
    "id": "toyota-us-sales",
    "category": "vehicles",
    "label": "Toyota and Lexus vehicles sold in the U.S.",
    "rate": 0.073916362,
    "period": "second",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "Toyota Motor North America 2024 sales",
    "sourceUrl": "https://pressroom.toyota.com/toyota-motor-north-america-reports-2024-u-s-sales-results/"
  },
  {
    "id": "crocs-shoes-sold",
    "category": "fashion",
    "label": "pairs of Crocs shoes sold",
    "rate": 4.024387152,
    "period": "second",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "Crocs 2024 full-year results transcript",
    "sourceUrl": "https://s22.q4cdn.com/133460125/files/doc_financials/2024/q4/Q4-FY-2024-Crocs-Inc-Transcript.pdf"
  },
  {
    "id": "doordash-orders",
    "category": "delivery",
    "label": "DoorDash orders placed",
    "rate": 81.850330824,
    "period": "second",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "DoorDash 2024 quarterly results (annual sum)",
    "sourceUrl": "https://ir.doordash.com/news/news-details/2025/DoorDash-Releases-Fourth-Quarter-and-Full-Year-2024-Financial-Results/default.aspx"
  },
  {
    "id": "airbus-deliveries",
    "category": "aviation",
    "label": "commercial airplanes delivered by Airbus",
    "rate": 0.000024273,
    "period": "second",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "Airbus 2024 deliveries",
    "sourceUrl": "https://www.airbus.com/en/newsroom/press-releases/2025-01-airbus-reports-766-commercial-aircraft-deliveries-in-2024",
    "minimumElapsedSeconds": 43200
  },
  {
    "id": "boeing-deliveries",
    "category": "aviation",
    "label": "commercial airplanes delivered by Boeing",
    "rate": 0.000011027,
    "period": "second",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "Boeing 2024 fourth-quarter results",
    "sourceUrl": "https://investors.boeing.com/investors/news/press-release-details/2025/Boeing-Reports-Fourth-Quarter-Results/default.aspx",
    "minimumElapsedSeconds": 86400
  },
  {
    "id": "ferrari-shipments",
    "category": "vehicles",
    "label": "Ferrari cars shipped",
    "rate": 0.000435775,
    "period": "second",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "Ferrari 2024 full-year results",
    "sourceUrl": "https://www.ferrari.com/en-EN/corporate/articles/2024-full-year-and-fourth-quarter-financial-results",
    "minimumElapsedSeconds": 3600
  },
  {
    "id": "global-beer-consumption",
    "category": "food",
    "label": "liters of beer enjoyed worldwide",
    "rate": 6151.291606459,
    "period": "second",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "Kirin Global Beer Consumption Report 2024",
    "sourceUrl": "https://www.kirinholdings.com/en/newsroom/release/2025/1222_01.pdf"
  },
  {
    "id": "global-wine-production",
    "category": "food",
    "label": "liters of wine made worldwide",
    "rate": 715.517022841,
    "period": "second",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "OIV State of the World Vine and Wine Sector 2024",
    "sourceUrl": "https://www.oiv.int/sites/default/files/2025-04/OIV-State_of_the_World_Vine-and-Wine-Sector-in-2024.pdf"
  },
  {
    "id": "global-wine-consumption",
    "category": "food",
    "label": "liters of wine enjoyed worldwide",
    "rate": 678.758840977,
    "period": "second",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "OIV State of the World Vine and Wine Sector 2024",
    "sourceUrl": "https://www.oiv.int/sites/default/files/2025-04/OIV-State_of_the_World_Vine-and-Wine-Sector-in-2024.pdf"
  },
  {
    "id": "global-shoes-made",
    "category": "fashion",
    "label": "pairs of shoes made worldwide",
    "rate": 757.345298755,
    "period": "second",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "World Footwear Yearbook 2025",
    "sourceUrl": "https://www.worldfootwear.com/news/footwear-production-rebounds-in-2024/10835.html"
  },
  {
    "id": "china-shoes-made",
    "category": "fashion",
    "label": "pairs of shoes made in China",
    "rate": 411.945141582,
    "period": "second",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "World Footwear Yearbook 2025",
    "sourceUrl": "https://www.worldfootwear.com/news/footwear-production-rebounds-in-2024/10835.html"
  },
  {
    "id": "global-crops-harvested",
    "category": "food",
    "label": "tons of crops harvested worldwide",
    "rate": 313.712069359,
    "period": "second",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "FAO agricultural production statistics, 2023",
    "sourceUrl": "https://www.fao.org/statistics/highlights-archive/highlights-detail/agricultural-production-statistics-2010-2023/en"
  },
  {
    "id": "global-sugarcane-harvested",
    "category": "food",
    "label": "tons of sugar cane harvested",
    "rate": 63.376175628,
    "period": "second",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "FAO agricultural production statistics, 2023",
    "sourceUrl": "https://www.fao.org/statistics/highlights-archive/highlights-detail/agricultural-production-statistics-2010-2023/en"
  },
  {
    "id": "global-fruit-vegetables-harvested",
    "category": "food",
    "label": "tons of fruit and vegetables harvested",
    "rate": 66.544984409,
    "period": "second",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "FAO agricultural production statistics, 2023",
    "sourceUrl": "https://www.fao.org/statistics/highlights-archive/highlights-detail/agricultural-production-statistics-2010-2023/en"
  },
  {
    "id": "global-oil-crops-harvested",
    "category": "food",
    "label": "tons of oil crops harvested",
    "rate": 28.297462418,
    "period": "second",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "FAO agricultural production statistics, 2023",
    "sourceUrl": "https://www.fao.org/statistics/highlights-archive/highlights-detail/agricultural-production-statistics-2010-2023/en"
  },
  {
    "id": "bananas-harvested",
    "category": "food",
    "label": "tons of bananas harvested",
    "rate": 4.404644206,
    "period": "second",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "FAO agricultural production analytical brief, 2023",
    "sourceUrl": "https://openknowledge.fao.org/bitstreams/df90e6cf-4178-4361-97d4-5154a9213877/download"
  },
  {
    "id": "watermelons-harvested",
    "category": "food",
    "label": "tons of watermelons harvested",
    "rate": 3.32724922,
    "period": "second",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "FAO agricultural production analytical brief, 2023",
    "sourceUrl": "https://openknowledge.fao.org/bitstreams/df90e6cf-4178-4361-97d4-5154a9213877/download"
  },
  {
    "id": "apples-harvested",
    "category": "food",
    "label": "tons of apples harvested",
    "rate": 3.073744518,
    "period": "second",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "FAO agricultural production analytical brief, 2023",
    "sourceUrl": "https://openknowledge.fao.org/bitstreams/df90e6cf-4178-4361-97d4-5154a9213877/download"
  },
  {
    "id": "grapes-harvested",
    "category": "food",
    "label": "tons of grapes harvested",
    "rate": 2.281542323,
    "period": "second",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "FAO agricultural production analytical brief, 2023",
    "sourceUrl": "https://openknowledge.fao.org/bitstreams/df90e6cf-4178-4361-97d4-5154a9213877/download"
  },
  {
    "id": "potatoes-harvested",
    "category": "food",
    "label": "tons of potatoes harvested",
    "rate": 12.136537633,
    "period": "second",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "FAO agricultural production analytical brief, 2023",
    "sourceUrl": "https://openknowledge.fao.org/bitstreams/df90e6cf-4178-4361-97d4-5154a9213877/download"
  },
  {
    "id": "cassava-harvested",
    "category": "food",
    "label": "tons of cassava harvested",
    "rate": 10.58382133,
    "period": "second",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "FAO agricultural production analytical brief, 2023",
    "sourceUrl": "https://openknowledge.fao.org/bitstreams/df90e6cf-4178-4361-97d4-5154a9213877/download"
  },
  {
    "id": "tomatoes-harvested",
    "category": "food",
    "label": "tons of tomatoes harvested",
    "rate": 6.08411286,
    "period": "second",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "FAO agricultural production analytical brief, 2023",
    "sourceUrl": "https://openknowledge.fao.org/bitstreams/df90e6cf-4178-4361-97d4-5154a9213877/download"
  },
  {
    "id": "onions-harvested",
    "category": "food",
    "label": "tons of onions harvested",
    "rate": 3.517377747,
    "period": "second",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "FAO agricultural production analytical brief, 2023",
    "sourceUrl": "https://openknowledge.fao.org/bitstreams/df90e6cf-4178-4361-97d4-5154a9213877/download"
  },
  {
    "id": "global-meat-produced",
    "category": "food",
    "label": "tons of meat produced worldwide",
    "rate": 11.851344842,
    "period": "second",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "FAO agricultural production statistics, 2024",
    "sourceUrl": "https://www.fao.org/statistics/highlights-archive/highlights-detail/agricultural-production-statistics-2010-2024/en"
  },
  {
    "id": "maize-harvested",
    "category": "food",
    "label": "tons of maize harvested",
    "rate": 38.659467133,
    "period": "second",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "FAO agricultural production analytical brief, 2024",
    "sourceUrl": "https://openknowledge.fao.org/bitstreams/23eaa328-ac5a-444e-ac62-80a636acd81f/download"
  },
  {
    "id": "shelter-animals-entering",
    "category": "animals",
    "label": "dogs and cats entering U.S. shelters and rescues",
    "rate": 0.183790909,
    "period": "second",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "Shelter Animals Count, 2024 annual analysis",
    "sourceUrl": "https://www.shelteranimalscount.org/explore-the-data/statistics-2024/"
  },
  {
    "id": "shelter-dogs-entering",
    "category": "animals",
    "label": "dogs entering U.S. shelters and rescues",
    "rate": 0.091895455,
    "period": "second",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "Shelter Animals Count, 2024 annual analysis",
    "sourceUrl": "https://www.shelteranimalscount.org/explore-the-data/statistics-2024/"
  },
  {
    "id": "shelter-cats-entering",
    "category": "animals",
    "label": "cats entering U.S. shelters and rescues",
    "rate": 0.091895455,
    "period": "second",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "Shelter Animals Count, 2024 annual analysis",
    "sourceUrl": "https://www.shelteranimalscount.org/explore-the-data/statistics-2024/"
  },
  {
    "id": "shelter-animals-adopted",
    "category": "animals",
    "label": "shelter dogs and cats adopted",
    "rate": 0.132850502,
    "period": "second",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "Shelter Animals Count, 2024 annual analysis",
    "sourceUrl": "https://www.shelteranimalscount.org/explore-the-data/statistics-2024/"
  },
  {
    "id": "shelter-dogs-adopted",
    "category": "animals",
    "label": "shelter dogs adopted",
    "rate": 0.063376176,
    "period": "second",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "Shelter Animals Count, 2024 annual analysis",
    "sourceUrl": "https://www.shelteranimalscount.org/explore-the-data/statistics-2024/"
  },
  {
    "id": "shelter-cats-adopted",
    "category": "animals",
    "label": "shelter cats adopted",
    "rate": 0.063376176,
    "period": "second",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "Shelter Animals Count, 2024 annual analysis",
    "sourceUrl": "https://www.shelteranimalscount.org/explore-the-data/statistics-2024/"
  },
  {
    "id": "fisheries-aquaculture-produced",
    "category": "animals",
    "label": "tons of fish and aquatic food produced worldwide",
    "rate": 7.0727812,
    "period": "second",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "FAO State of World Fisheries and Aquaculture 2024",
    "sourceUrl": "https://www.fao.org/newsroom/detail/fao-report-global-fisheries-and-aquaculture-production-reaches-a-new-record-high/en"
  },
  {
    "id": "aquatic-animals-produced",
    "category": "animals",
    "label": "tons of aquatic animals raised and caught worldwide",
    "rate": 5.874971481,
    "period": "second",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "FAO State of World Fisheries and Aquaculture 2024",
    "sourceUrl": "https://www.fao.org/newsroom/detail/fao-report-global-fisheries-and-aquaculture-production-reaches-a-new-record-high/en"
  },
  {
    "id": "algae-produced",
    "category": "animals",
    "label": "tons of algae grown worldwide",
    "rate": 1.197809719,
    "period": "second",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "FAO State of World Fisheries and Aquaculture 2024",
    "sourceUrl": "https://www.fao.org/newsroom/detail/fao-report-global-fisheries-and-aquaculture-production-reaches-a-new-record-high/en"
  },
  {
    "id": "aquaculture-produced",
    "category": "animals",
    "label": "tons of aquatic food produced by fish farms",
    "rate": 4.147970695,
    "period": "second",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "FAO State of World Fisheries and Aquaculture 2024",
    "sourceUrl": "https://www.fao.org/newsroom/detail/fao-report-global-fisheries-and-aquaculture-production-reaches-a-new-record-high/en"
  },
  {
    "id": "farmed-aquatic-animals",
    "category": "animals",
    "label": "tons of aquatic animals raised by fish farms",
    "rate": 2.99135549,
    "period": "second",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "FAO State of World Fisheries and Aquaculture 2024",
    "sourceUrl": "https://www.fao.org/newsroom/detail/fao-report-global-fisheries-and-aquaculture-production-reaches-a-new-record-high/en"
  },
  {
    "id": "wild-caught-fish",
    "category": "animals",
    "label": "tons of aquatic animals caught by fishers",
    "rate": 2.924810505,
    "period": "second",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "FAO State of World Fisheries and Aquaculture 2024",
    "sourceUrl": "https://www.fao.org/newsroom/detail/fao-report-global-fisheries-and-aquaculture-production-reaches-a-new-record-high/en"
  },
  {
    "id": "ebird-observations",
    "category": "animals",
    "label": "bird observations shared on eBird",
    "rate": 8.492407534,
    "period": "second",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "eBird 2024 year in review",
    "sourceUrl": "https://ebird.org/news/2024-year-in-review"
  },
  {
    "id": "new-ebirders",
    "category": "animals",
    "label": "new birdwatchers joining eBird",
    "rate": 0.003865947,
    "period": "second",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "eBird 2024 year in review",
    "sourceUrl": "https://ebird.org/news/2024-year-in-review",
    "minimumElapsedSeconds": 3600
  },
  {
    "id": "ebird-research-papers",
    "category": "science",
    "label": "research papers using eBird data",
    "rate": 0.000007859,
    "period": "second",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "eBird 2024 year in review",
    "sourceUrl": "https://ebird.org/news/2024-year-in-review",
    "minimumElapsedSeconds": 604800
  },
  {
    "id": "new-species-described",
    "category": "science",
    "label": "new species described by California Academy scientists",
    "rate": 0.000004373,
    "period": "second",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "California Academy of Sciences, 2024 species report",
    "sourceUrl": "https://www.calacademy.org/press/releases/california-academy-of-sciences-describes-138-new-species-in-2024",
    "minimumElapsedSeconds": 604800
  },
  {
    "id": "patent-applications",
    "category": "science",
    "label": "patent applications filed",
    "rate": 0.117245925,
    "period": "second",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "WIPO World Intellectual Property Indicators, 2024",
    "sourceUrl": "https://www.wipo.int/en/web/ip-statistics/w/news/2025/world-intellectual-property-indicators-global-patent-and-design-filings-reach-new-records-in-2024-trademarks-flat"
  },
  {
    "id": "trademark-applications",
    "category": "science",
    "label": "trademark applications filed",
    "rate": 0.481658935,
    "period": "second",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "WIPO World Intellectual Property Indicators, 2024",
    "sourceUrl": "https://www.wipo.int/en/web/ip-statistics/w/news/2025/world-intellectual-property-indicators-global-patent-and-design-filings-reach-new-records-in-2024-trademarks-flat"
  },
  {
    "id": "industrial-design-applications",
    "category": "science",
    "label": "industrial design applications filed",
    "rate": 0.050700941,
    "period": "second",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "WIPO World Intellectual Property Indicators, 2024",
    "sourceUrl": "https://www.wipo.int/en/web/ip-statistics/w/news/2025/world-intellectual-property-indicators-global-patent-and-design-filings-reach-new-records-in-2024-trademarks-flat"
  },
  {
    "id": "orbital-launches",
    "category": "science",
    "label": "rocket launches reaching orbit",
    "rate": 0.000008207,
    "period": "second",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "BryceTech Global Space Launch Activity 2024",
    "sourceUrl": "https://brycetech.com/reports/report-documents/global-space-launch-activity-2024/",
    "minimumElapsedSeconds": 604800
  },
  {
    "id": "spacecraft-deployed",
    "category": "science",
    "label": "new spacecraft deployed",
    "rate": 0.000091895,
    "period": "second",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "BryceTech Global Space Launch Activity 2024",
    "sourceUrl": "https://brycetech.com/reports/report-documents/global-space-launch-activity-2024/",
    "minimumElapsedSeconds": 21600
  },
  {
    "id": "youtube-videos-uploaded",
    "category": "social",
    "label": "videos uploaded to YouTube",
    "rate": 231.481481481,
    "period": "second",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "YouTube press facts",
    "sourceUrl": "https://blog.youtube/press/"
  },
  {
    "id": "youtube-shorts-views",
    "category": "social",
    "label": "YouTube Shorts views",
    "rate": 2314814.814814815,
    "period": "second",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "YouTube press facts",
    "sourceUrl": "https://blog.youtube/press/"
  },
  {
    "id": "snapchat-snaps-created",
    "category": "social",
    "label": "Snaps created by Snapchatters",
    "rate": 63657.407407407,
    "period": "second",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "Snap 2025 year in review",
    "sourceUrl": "https://newsroom.snap.com/2trillion-snaps-in-2025"
  },
  {
    "id": "snapchat-talk-minutes",
    "category": "social",
    "label": "minutes spent talking on Snapchat",
    "rate": 19675.925925926,
    "period": "second",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "Snapchat Generation Report",
    "sourceUrl": "https://newsroom.snap.com/snapchat-generation-report"
  },
  {
    "id": "snapchat-ar-users",
    "category": "social",
    "label": "Snapchatters using augmented reality",
    "rate": 4050.925925926,
    "period": "second",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "Snap newsroom facts",
    "sourceUrl": "https://newsroom.snap.com/"
  },
  {
    "id": "meta-messages-sent",
    "category": "social",
    "label": "messages sent on Meta apps",
    "rate": 1157407.407407407,
    "period": "second",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "Meta messaging announcement",
    "sourceUrl": "https://about.fb.com/news/2020/09/new-messaging-features-for-instagram/"
  },
  {
    "id": "reddit-content-created",
    "category": "social",
    "label": "Reddit posts and comments shared",
    "rate": 377.415458937,
    "period": "second",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "Reddit H2 2024 transparency report",
    "sourceUrl": "https://redditinc.com/policies/transparency-report-july-to-december-2024"
  },
  {
    "id": "tiktok-videos-posted",
    "category": "social",
    "label": "TikTok videos posted",
    "rate": 393.518518519,
    "period": "second",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "Harvard Business School music-demand study",
    "sourceUrl": "https://www.hbs.edu/ris/download.aspx?name=25-014.pdf"
  },
  {
    "id": "live-nation-fans",
    "category": "culture",
    "label": "fans attending Live Nation shows",
    "rate": 4.753213172,
    "period": "second",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "Live Nation 2024 annual report",
    "sourceUrl": "https://investors.livenationentertainment.com/sec-filings/annual-reports/content/0001193125-25-094946/0001193125-25-094946.pdf"
  },
  {
    "id": "live-nation-venue-fans",
    "category": "culture",
    "label": "fans attending Live Nation venues and festivals",
    "rate": 1.901285269,
    "period": "second",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "Live Nation 2024 annual report",
    "sourceUrl": "https://investors.livenationentertainment.com/sec-filings/annual-reports/content/0001193125-25-094946/0001193125-25-094946.pdf"
  },
  {
    "id": "live-nation-shows",
    "category": "culture",
    "label": "Live Nation shows produced",
    "rate": 0.001584404,
    "period": "second",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "Live Nation 2024 annual report",
    "sourceUrl": "https://investors.livenationentertainment.com/sec-filings/annual-reports/content/0001193125-25-094946/0001193125-25-094946.pdf",
    "minimumElapsedSeconds": 1200
  },
  {
    "id": "international-tourists",
    "category": "travel",
    "label": "international tourist arrivals",
    "rate": 44.36332294,
    "period": "second",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "UN Tourism 2024 World Tourism Barometer",
    "sourceUrl": "https://www.untourism.int/news/international-tourism-recovers-pre-pandemic-levels-in-2024"
  },
  {
    "id": "tourism-exports",
    "category": "economy",
    "label": "dollars earned from international tourism exports",
    "rate": 60207.366846655,
    "period": "second",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "UN Tourism 2024 World Tourism Barometer",
    "sourceUrl": "https://www.untourism.int/news/international-tourism-recovers-pre-pandemic-levels-in-2024"
  },
  {
    "id": "tourism-gdp",
    "category": "economy",
    "label": "dollars added to the global economy by travel and tourism",
    "rate": 345400.157172916,
    "period": "second",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "World Bank tourism facts",
    "sourceUrl": "https://www.worldbank.org/ext/en/topic/tourism"
  },
  {
    "id": "foreign-exchange-trading",
    "category": "economy",
    "label": "dollars traded in foreign-exchange markets",
    "rate": 111111111.1111111,
    "period": "second",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "BIS 2025 Triennial FX Survey",
    "sourceUrl": "https://www.bis.org/statistics/rpfx25_fx.htm"
  },
  {
    "id": "global-trade",
    "category": "economy",
    "label": "dollars in goods and services traded across borders",
    "rate": 1045706.897862955,
    "period": "second",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "UNCTAD Global Trade Update, 2024",
    "sourceUrl": "https://unctad.org/news/global-trade-hits-record-33-trillion-2024-driven-services-and-developing-economies"
  },
  {
    "id": "remittances",
    "category": "economy",
    "label": "dollars sent home in remittances",
    "rate": 21706.34015261,
    "period": "second",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "World Bank 2024 remittance estimates",
    "sourceUrl": "https://blogs.worldbank.org/en/peoplemove/in-2024--remittance-flows-to-low--and-middle-income-countries-ar"
  },
  {
    "id": "global-games-revenue",
    "category": "economy",
    "label": "dollars spent on games worldwide",
    "rate": 5982.710979289,
    "period": "second",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "Newzoo Global Games Market Report 2025",
    "sourceUrl": "https://newzoo.com/articles/global-games-market-189-billion-2025/"
  },
  {
    "id": "stablecoin-transactions",
    "category": "crypto",
    "label": "stablecoin transactions",
    "rate": 139.906389906,
    "period": "second",
    "decimalPlaces": 0,
    "format": "compact",
    "sourceLabel": "a16z State of Crypto 2024",
    "sourceUrl": "https://a16zcrypto.com/posts/article/state-of-crypto-report-2024/"
  }
];
